-- ============================================================================
-- RCW Phase 1 Schema Apply — TRANSACTIONAL
-- ============================================================================
-- Generated by:  wdws agent (autonomous Phase 1 staging)
-- Generated at:  2026-04-29 (replaces /opt/wdws/rcw_research/schema_design.sql
--                for direct application)
-- Operator:      William J. Nelson — apply via psql, not autonomously
-- Status:        APPLY-READY — atomic single-transaction migration
--
-- Pre-execution requirements:
--   - PostgreSQL 17+ with pgvector extension loaded
--   - core.tags, core.documents, core.document_tags, usc.* schemas exist
--   - session_preload_libraries='vector' active (verified at OS level)
--
-- This script is atomic. Either the entire transaction commits or
-- nothing changes. If any pre-flight guard or post-apply guard fails,
-- the whole transaction is automatically ROLLed BACK by the
-- ON_ERROR_STOP / RAISE EXCEPTION combination.
--
-- Companion documents:
--   /opt/wdws/rcw_research/rcw_source_findings.md
--   /opt/wdws/rcw_research/cross_jurisdiction_design.md
--   /opt/wdws/rcw_research/litigation_priority_addendum.md
--   /opt/wdws/rcw_research/schema_design.sql      (review-only; this file
--                                                  supersedes it for apply)
-- ============================================================================
--
-- HOW TO APPLY (operator instructions):
--
--   psql -h 127.0.0.1 -U wdws -d wdws -f /opt/wdws/rcw_research/schema_apply.sql
--
-- Expected behavior:
--   1. Pre-flight guards print "PASS" NOTICE or RAISE EXCEPTION
--   2. §1 schema + §2 indexes + §3 tag inserts execute
--   3. §LEGACY-MIGRATION re-points 5 join rows + deletes 2 legacy tag rows
--   4. §4 USC retroactive tagging adds 11,678 join rows
--   5. Post-apply guards print "PASS" NOTICE or RAISE EXCEPTION
--   6. COMMIT succeeds OR full ROLLBACK on any failure
--   7. Post-commit verification SELECTs print to stdout
--
-- Capture the entire psql output (stdout + stderr) and paste back to the
-- agent for parsing and Phase 2 authorization decision.
--
-- Estimated wall time: under 30 seconds total. The 11,678-row USC retro-tag
-- INSERT is the largest operation; everything else is trivial.
--
-- If the script raises an EXCEPTION, the transaction rolls back automatically.
-- Database is unchanged. Report the exception text and any preceding NOTICE
-- messages back to the agent.
--
-- DO NOT modify this file before applying. If changes are needed, regenerate
-- via the agent and re-review.
-- ============================================================================

\set ON_ERROR_STOP on
\timing on

BEGIN;


-- ============================================================================
-- §0  PRE-EXECUTION GUARDS (raise EXCEPTION on mismatch — triggers rollback)
-- ============================================================================
-- Confirms the live schema is in the state the staging design assumed. Any
-- drift since the 2026-04-28 introspection halts the transaction before any
-- writes.

DO $$
DECLARE
  wlad_count           INTEGER;
  pra_count            INTEGER;
  rcw_schema_exists    INTEGER;
  collision_count      INTEGER;
  usc_doc_count        INTEGER;
  jurisdiction_intact  INTEGER;
BEGIN
  -- §0.1 Legacy wlad has exactly 4 doc associations (will migrate)
  SELECT COUNT(*) INTO wlad_count FROM core.document_tags WHERE tag_id = 242;
  IF wlad_count <> 4 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.1]: legacy wlad (id=242) has % doc associations, expected 4. Halt — investigate before retry.', wlad_count;
  END IF;

  -- §0.2 Legacy pra has exactly 1 doc association (will migrate)
  SELECT COUNT(*) INTO pra_count FROM core.document_tags WHERE tag_id = 606;
  IF pra_count <> 1 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.2]: legacy pra (id=606) has % doc associations, expected 1. Halt — investigate before retry.', pra_count;
  END IF;

  -- §0.3 rcw schema does not yet exist
  SELECT COUNT(*) INTO rcw_schema_exists FROM information_schema.schemata WHERE schema_name = 'rcw';
  IF rcw_schema_exists <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.3]: rcw schema already exists. Halt — investigate state before retry.';
  END IF;

  -- §0.4 None of the proposed RCW slugs collide with anything that snuck in since investigation
  SELECT COUNT(*) INTO collision_count FROM core.tags
    WHERE slug IN (
      'wlad','pra','oma','bii',
      'wa-civil-procedure','wa-criminal-procedure',
      'wa-mental-health','wa-public-assistance',
      'wa-domestic-relations','wa-probate',
      'wa-public-employment','wa-courts','wa-constitution',
      'cpa-wa','writs-wa','child-abuse-wa','gal-wa',
      'rcw','state-statute',
      'rcw-repealed','rcw-recodified','rcw-decodified',
      'rcw-expired','rcw-reserved','rcw-suspended',
      'federal-usc','state-wa-rcw'
    );
  IF collision_count <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.4]: % proposed slug(s) already exist (someone added them since 2026-04-28 investigation). Halt — investigate before retry.', collision_count;
  END IF;

  -- §0.5 USC corpus is the expected 11,678 documents (will be retro-tagged in §4)
  SELECT COUNT(*) INTO usc_doc_count FROM core.documents
    WHERE document_type='statute' AND domain='legal';
  IF usc_doc_count <> 11678 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.5]: USC document count is %, expected 11678. Halt — investigate before retry.', usc_doc_count;
  END IF;

  -- §0.6 Existing jurisdiction:wa:ada tag is intact (sanity check that we are
  --       not accidentally about to clobber an existing record)
  SELECT COUNT(*) INTO jurisdiction_intact FROM core.tags
    WHERE category='jurisdiction' AND slug='wa:ada';
  IF jurisdiction_intact <> 1 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.6]: jurisdiction:wa:ada tag missing — schema state unexpected. Halt.';
  END IF;

  RAISE NOTICE 'Pre-flight guards: PASS (wlad=4, pra=1, rcw schema absent, 0 slug collisions, USC=11678, jurisdiction:wa:ada intact)';
END $$;


-- ============================================================================
-- §1  RCW SCHEMA + TABLES
-- ============================================================================

CREATE SCHEMA rcw;
COMMENT ON SCHEMA rcw IS
  'Revised Code of Washington — state statutory corpus parallel to usc.*. '
  'Phase 4 ingest writes here; Phase 6 retrieval reads via core.documents/'
  'document_chunks (FK from rcw.sections.document_id). Designed 2026-04-28; '
  'see /opt/wdws/rcw_research/schema_design.sql for full design rationale.';


-- §1.1 rcw.titles
CREATE TABLE rcw.titles (
    title_number      TEXT PRIMARY KEY,
    title_name        TEXT NOT NULL,
    publication_date  DATE NOT NULL,
    last_ingested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    chapter_count     INTEGER,
    section_count     INTEGER,
    notes             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE rcw.titles IS
  'One row per RCW title (1, 2, 9A, 23B, …, 91). Populated at start of '
  'Phase 4 from app.leg.wa.gov landing-page title list. publication_date '
  'is the canonical version anchor — currently 2025-08-15 (RCW landing '
  'page Last update: marker as of 2026-04-28).';


-- §1.2 rcw.chapters
CREATE TABLE rcw.chapters (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title_number     TEXT NOT NULL REFERENCES rcw.titles(title_number),
    chapter_number   TEXT NOT NULL,
    chapter_heading  TEXT NOT NULL,
    sort_order       INTEGER NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (title_number, chapter_number)
);
COMMENT ON TABLE rcw.chapters IS
  'One row per RCW chapter (e.g. 4.04, 42.56, 9A.04, 11.96A). '
  'Populated incrementally during Phase 4 priority-sequence ingest.';


-- §1.3 rcw.sections (full_text NULLable + 5-flag CHECK constraint per operator decision #1)
CREATE TABLE rcw.sections (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id              UUID NOT NULL UNIQUE REFERENCES core.documents(id) ON DELETE CASCADE,
    title_number             TEXT NOT NULL REFERENCES rcw.titles(title_number),
    chapter_id               UUID REFERENCES rcw.chapters(id),
    section_number           TEXT NOT NULL,
    canonical_citation       TEXT NOT NULL,
    section_heading          TEXT NOT NULL,
    -- Mutually-non-exclusive booleans rather than enum because WA dispositions
    -- can combine flags (e.g., 'expired AND recodified').
    is_repealed              BOOLEAN NOT NULL DEFAULT FALSE,
    is_recodified            BOOLEAN NOT NULL DEFAULT FALSE,
    is_decodified            BOOLEAN NOT NULL DEFAULT FALSE,
    is_expired               BOOLEAN NOT NULL DEFAULT FALSE,
    is_reserved              BOOLEAN NOT NULL DEFAULT FALSE,
    recodified_to            TEXT,
    effective_date           DATE,
    enacted_by_session_law   TEXT,
    -- full_text NULLable per Phase 1 operator decision #1. Active sections
    -- must have text; ghost rows (any of 5 status flags) must NOT have text
    -- (initial state) until a Phase 7+ archive sweep backfills prior-version
    -- text from the certified RCW Archive PDFs. CHECK below enforces this.
    full_text                TEXT,
    -- source_html parallel to full_text — also NULL for ghost rows.
    source_html              TEXT,
    publication_date         DATE NOT NULL,
    -- WA does NOT have USC's 'court_rule' or 'reorganization_plan' variants.
    -- Court rules are Phase 8 backlog (separate ingest).
    unit_type                TEXT NOT NULL DEFAULT 'section',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (canonical_citation, publication_date),

    -- Operator-approved CHECK (Phase 1 decision #1, extended to all 5 ghost
    -- flags per operator decision #1 acknowledgment).
    CONSTRAINT chk_section_text_status_invariant CHECK (
      (full_text IS NOT NULL AND full_text <> ''
       AND NOT (is_repealed OR is_recodified OR is_decodified
                OR is_expired OR is_reserved))
      OR
      ((is_repealed OR is_recodified OR is_decodified
        OR is_expired OR is_reserved)
       AND (full_text IS NULL OR full_text = ''))
    ),

    CONSTRAINT chk_unit_type CHECK (unit_type IN ('section','reserved')),

    -- If is_recodified=TRUE, recodified_to must be populated. Per operator
    -- decision #2.
    CONSTRAINT chk_recodified_target CHECK (
      NOT is_recodified OR (recodified_to IS NOT NULL AND recodified_to <> '')
    )
);
COMMENT ON TABLE rcw.sections IS
  'One row per RCW section. Three flavors: '
  '(a) Live current section — full_text populated, no status flags set, '
  '    chunked + embedded into core.document_chunks. ~45,000 rows expected. '
  '(b) Recodified ghost — is_recodified=TRUE, recodified_to set, full_text NULL. '
  '    Allows historical-citation lookups (e.g., RCW 42.17.320 → 42.56.520). '
  '(c) Repealed/decodified/expired/reserved ghost — corresponding status flag '
  '    TRUE, full_text NULL. '
  'Ghost rows have FK to core.documents but the document row is a stub '
  '(short pointer text in full_content; no embeddings). '
  'See cross_jurisdiction_design.md §6 for retrieval semantics.';


-- §1.4 rcw.cross_references
CREATE TABLE rcw.cross_references (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_section_id   UUID NOT NULL REFERENCES rcw.sections(id) ON DELETE CASCADE,
    target_citation     TEXT NOT NULL,
    target_section_id   UUID REFERENCES rcw.sections(id),
    target_jurisdiction TEXT NOT NULL,
    context_snippet     TEXT,
    ref_type            TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_target_jurisdiction CHECK (
      target_jurisdiction IN (
        'state-wa-rcw','federal-usc','wac','cfr',
        'wa-court-rule','session-law','wa-constitution'
      )
    ),
    CONSTRAINT chk_ref_type CHECK (
      ref_type IN ('reference','recodification','cross-statute','see-also','authority')
    )
);
COMMENT ON TABLE rcw.cross_references IS
  'Cross-citations parsed from RCW section bodies. Includes inbound recodification '
  'pointers (target_jurisdiction=state-wa-rcw, ref_type=recodification — populated '
  'when a section''s source-credit bracket includes "Formerly RCW X.YY.ZZZ"). '
  'target_section_id is a post-Phase-4 resolution step; nullable until then.';


-- §1.5 rcw.section_history
CREATE TABLE rcw.section_history (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_id      UUID NOT NULL REFERENCES rcw.sections(id) ON DELETE CASCADE,
    session_law     TEXT NOT NULL,
    session_year    INTEGER,
    session_law_pdf TEXT,
    action_type     TEXT,
    action_summary  TEXT,
    sort_order      INTEGER NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_action_type CHECK (
      action_type IS NULL OR action_type IN ('enacted','amended','recodified','repealed','reorganized')
    )
);
COMMENT ON TABLE rcw.section_history IS
  'Parsed from the [ ... ] source-credit brackets at the end of each section body. '
  'Each linked session-law citation gets one row. session_year is NULL for pre-'
  'codification references like "Code 1881 s 1" or "RRS s 143". sort_order '
  'preserves the in-bracket order — most recent first per RCW publication '
  'convention, so sort_order=1 is the latest amendment.';


-- §1.6 rcw.section_notes (note_type permissive TEXT — no CHECK)
CREATE TABLE rcw.section_notes (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_id    UUID NOT NULL REFERENCES rcw.sections(id) ON DELETE CASCADE,
    note_type     TEXT NOT NULL,
    note_topic    TEXT,
    note_heading  TEXT,
    note_text     TEXT NOT NULL,
    sort_order    INTEGER NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE rcw.section_notes IS
  'Parsed from the <h3>NOTES:</h3> block (or <h3>Notes:</h3> in single-section view) '
  'after each section''s source-credit bracket. note_type is permissive TEXT '
  'rather than a strict enum — see Phase 0 findings §2.7 for the observed '
  'catalog (Reviser''s note, Findings, Effective date, Construction, Conflict '
  'with federal requirements, Expiration date, Severability, Short title, '
  'Application, Finding, Legislative findings, Purpose). Add a CHECK constraint '
  'in Phase 5 once the corpus is full and the distribution is known.';


-- §1.7 rcw.ingestion_runs (adds 'paused' to USC's status set per operator decision #3)
CREATE TABLE rcw.ingestion_runs (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    publication_date      DATE NOT NULL,
    started_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at          TIMESTAMPTZ,
    titles_planned        SMALLINT,
    titles_completed      SMALLINT,
    chapters_ingested     INTEGER,
    sections_ingested     INTEGER,
    chunks_ingested       INTEGER,
    embeddings_completed  INTEGER,
    status                TEXT NOT NULL DEFAULT 'running',
    notes                 TEXT,

    CONSTRAINT chk_ingestion_status CHECK (
      status IN ('running','completed','failed','partial','paused')
    )
);
COMMENT ON TABLE rcw.ingestion_runs IS
  'One row per Phase 4 ingest invocation (priority-core, long-tail, Phase 7 '
  'differential update). Populated incrementally as titles/chapters complete. '
  'Adds a "paused" status to USC''s set, for the explicit pause-checkpoints '
  '(A and B) in the Phase 4 priority sequence.';


-- ============================================================================
-- §2  RCW INDEXES (24 total)
-- ============================================================================

-- Title and chapter lookups
CREATE INDEX idx_rcw_chapters_title             ON rcw.chapters(title_number);
CREATE INDEX idx_rcw_sections_title             ON rcw.sections(title_number);
CREATE INDEX idx_rcw_sections_chapter           ON rcw.sections(chapter_id);

-- Citation-lookup hot path (Pattern (b))
CREATE INDEX idx_rcw_sections_citation          ON rcw.sections(canonical_citation);

-- Publication-date filtering
CREATE INDEX idx_rcw_sections_publication       ON rcw.sections(publication_date);

-- Status-flag partial indexes
CREATE INDEX idx_rcw_sections_repealed          ON rcw.sections(canonical_citation) WHERE is_repealed   = TRUE;
CREATE INDEX idx_rcw_sections_recodified        ON rcw.sections(canonical_citation) WHERE is_recodified = TRUE;
CREATE INDEX idx_rcw_sections_decodified        ON rcw.sections(canonical_citation) WHERE is_decodified = TRUE;
CREATE INDEX idx_rcw_sections_expired           ON rcw.sections(canonical_citation) WHERE is_expired    = TRUE;
CREATE INDEX idx_rcw_sections_reserved          ON rcw.sections(canonical_citation) WHERE is_reserved   = TRUE;

-- Effective-date filtering (sparse)
CREATE INDEX idx_rcw_sections_effective_date    ON rcw.sections(effective_date) WHERE effective_date IS NOT NULL;

-- Unit-type partial index (default 'section' excluded, like USC)
CREATE INDEX idx_rcw_sections_unit_type         ON rcw.sections(unit_type) WHERE unit_type <> 'section';

-- Recodification target — supports forward-redirect lookups
CREATE INDEX idx_rcw_sections_recodified_to     ON rcw.sections(recodified_to) WHERE recodified_to IS NOT NULL;

-- Full-text search (parallel to usc.idx_sections_text_fts)
CREATE INDEX idx_rcw_sections_text_fts          ON rcw.sections USING gin(to_tsvector('english', COALESCE(full_text,'')));

-- Cross-references — both directions
CREATE INDEX idx_rcw_xref_source                ON rcw.cross_references(source_section_id);
CREATE INDEX idx_rcw_xref_target                ON rcw.cross_references(target_citation);
CREATE INDEX idx_rcw_xref_target_jurisdiction   ON rcw.cross_references(target_jurisdiction);
CREATE INDEX idx_rcw_xref_ref_type              ON rcw.cross_references(ref_type);

-- Section history
CREATE INDEX idx_rcw_history_section            ON rcw.section_history(section_id);
CREATE INDEX idx_rcw_history_session_law        ON rcw.section_history(session_law);
CREATE INDEX idx_rcw_history_year               ON rcw.section_history(session_year) WHERE session_year IS NOT NULL;

-- Section notes
CREATE INDEX idx_rcw_notes_section              ON rcw.section_notes(section_id);
CREATE INDEX idx_rcw_notes_type                 ON rcw.section_notes(note_type);
CREATE INDEX idx_rcw_notes_topic                ON rcw.section_notes(note_topic) WHERE note_topic IS NOT NULL;


-- ============================================================================
-- §3  TAG TAXONOMY ADDITIONS
-- ============================================================================
-- All inserts use ON CONFLICT (slug) DO NOTHING for idempotency. Slug is
-- globally unique (tags_slug_key); pre-flight §0.4 already verified zero
-- collisions, so ON CONFLICT is belt-and-suspenders only.


-- §3a  code-jurisdiction category — corpus-discriminator
INSERT INTO core.tags (slug, name, category, description) VALUES
  ('federal-usc',
   'Federal USC',
   'code-jurisdiction',
   'Document is a section of the United States Code (federal statutory law).'),
  ('state-wa-rcw',
   'State WA RCW',
   'code-jurisdiction',
   'Document is a section of the Revised Code of Washington (Washington State statutory law).')
ON CONFLICT (slug) DO NOTHING;


-- §3b  rcw-meta category — corpus / status structural tags
INSERT INTO core.tags (slug, name, category, description) VALUES
  ('rcw',
   'RCW',
   'rcw-meta',
   'Document is a section of the Revised Code of Washington.'),
  ('state-statute',
   'State Statute',
   'rcw-meta',
   'State statutory law (as opposed to court rule, regulation, constitutional provision).'),
  ('rcw-repealed',
   'RCW Repealed',
   'rcw-meta',
   'RCW section was repealed; preserved as a ghost row for retrospective citation lookup.'),
  ('rcw-recodified',
   'RCW Recodified',
   'rcw-meta',
   'RCW section was recodified to a different citation; ghost row carries the recodified_to pointer.'),
  ('rcw-decodified',
   'RCW Decodified',
   'rcw-meta',
   'RCW section was decodified (removed from the code); rare.'),
  ('rcw-expired',
   'RCW Expired',
   'rcw-meta',
   'RCW section''s sunset clause fired; ghost row preserved.'),
  ('rcw-reserved',
   'RCW Reserved',
   'rcw-meta',
   'RCW section number is reserved; never had text.'),
  ('rcw-suspended',
   'RCW Suspended',
   'rcw-meta',
   'RCW section''s effective application is suspended pending some condition; rare.')
ON CONFLICT (slug) DO NOTHING;


-- §3c  legal-framework topical tags — RCW additions (must precede §LEGACY-MIGRATION)
INSERT INTO core.tags (slug, name, category, description) VALUES
  ('wlad',
   'WLAD',
   'legal-framework',
   'Washington Law Against Discrimination — RCW chapter 49.60. Civil-rights statute analogue/pair to federal Title VII / ADA.'),
  ('pra',
   'PRA',
   'legal-framework',
   'Washington Public Records Act — RCW chapter 42.56. Records-access statute, parallels FOIA (5 U.S.C. § 552).'),
  ('oma',
   'OMA',
   'legal-framework',
   'Washington Open Public Meetings Act — RCW chapter 42.30.'),
  ('bii',
   'BII',
   'legal-framework',
   'Washington Industrial Insurance / workers'' compensation — RCW Title 51. Includes BIIA appeals (chapter 51.52).'),
  ('wa-civil-procedure',
   'WA Civil Procedure',
   'legal-framework',
   'Washington civil-procedure statutes — RCW Title 4. Includes statutes of limitations (4.16), claims against governmental entities (4.96), frivolous-action fees (4.84).'),
  ('wa-criminal-procedure',
   'WA Criminal Procedure',
   'legal-framework',
   'Washington criminal procedure — RCW Title 10 plus procedure-flavored sections in Titles 9 and 9A. Distinct from federal `criminal-procedure` tag.'),
  ('wa-mental-health',
   'WA Mental Health',
   'legal-framework',
   'Washington behavioral-health / civil-commitment statutes — RCW Title 71.'),
  ('wa-public-assistance',
   'WA Public Assistance',
   'legal-framework',
   'Washington public-assistance statutes — RCW Title 74. Includes vulnerable-adult civil cause of action (74.34).'),
  ('wa-domestic-relations',
   'WA Domestic Relations',
   'legal-framework',
   'Washington domestic-relations statutes — RCW Title 26. Includes parenting-plan restrictions (26.09.191) and child-abuse reporting (26.44).'),
  ('wa-probate',
   'WA Probate',
   'legal-framework',
   'Washington probate / trust law — RCW Title 11. Includes incapacitated-person doctrine (11.88.010(1)) and TEDRA (11.96A).'),
  ('wa-public-employment',
   'WA Public Employment',
   'legal-framework',
   'Washington public-employment / civil-service / pensions — RCW Title 41. Includes State Civil Service Law (41.06) and PERS (41.40).'),
  ('wa-courts',
   'WA Courts',
   'legal-framework',
   'Washington courts of record — RCW Title 2. Includes Supreme Court rule-making power (2.04) — the statutory authority under which GR 31 / GR 31.1 are promulgated.'),
  ('wa-constitution',
   'WA Constitution',
   'legal-framework',
   'Marker for sections that cross-reference the Washington State Constitution. (The Constitution itself is Phase 8 backlog.)'),
  ('cpa-wa',
   'WA Consumer Protection Act',
   'legal-framework',
   'Washington Consumer Protection Act — RCW chapter 19.86. Pleads in tandem with WLAD and consumer-facing PRA refusals.'),
  ('writs-wa',
   'WA Writs',
   'legal-framework',
   'Washington writs (mandamus, prohibition, certiorari) — RCW chapter 7.16. Relevant to records-access enforcement and judicial-review compulsion.'),
  ('child-abuse-wa',
   'WA Child Abuse Reporting',
   'legal-framework',
   'Washington child-abuse mandatory-reporting framework — RCW chapter 26.44. Including 26.44.030 reporting duty and 26.44.186/.188 records access.'),
  ('gal-wa',
   'WA GAL Framework',
   'legal-framework',
   'Washington Guardian ad Litem framework — cuts across RCW Titles 11 (probate), 26 (domestic relations), 26.44 (child abuse).')
ON CONFLICT (slug) DO NOTHING;


-- §3d  rcw-title category — 100 title rows
INSERT INTO core.tags (slug, name, category, description) VALUES
  ('rcw-title-1',     'RCW Title 1 — General Provisions',                                            'rcw-title', 'RCW Title 1: GENERAL PROVISIONS'),
  ('rcw-title-2',     'RCW Title 2 — Courts of Record',                                              'rcw-title', 'RCW Title 2: COURTS OF RECORD'),
  ('rcw-title-3',     'RCW Title 3 — District Courts—Courts of Limited Jurisdiction',                'rcw-title', 'RCW Title 3: DISTRICT COURTS—COURTS OF LIMITED JURISDICTION'),
  ('rcw-title-4',     'RCW Title 4 — Civil Procedure',                                               'rcw-title', 'RCW Title 4: CIVIL PROCEDURE'),
  ('rcw-title-5',     'RCW Title 5 — Evidence',                                                       'rcw-title', 'RCW Title 5: EVIDENCE'),
  ('rcw-title-6',     'RCW Title 6 — Enforcement of Judgments',                                       'rcw-title', 'RCW Title 6: ENFORCEMENT OF JUDGMENTS'),
  ('rcw-title-7',     'RCW Title 7 — Special Proceedings and Actions',                                'rcw-title', 'RCW Title 7: SPECIAL PROCEEDINGS AND ACTIONS'),
  ('rcw-title-8',     'RCW Title 8 — Eminent Domain',                                                 'rcw-title', 'RCW Title 8: EMINENT DOMAIN'),
  ('rcw-title-9',     'RCW Title 9 — Crimes and Punishments',                                         'rcw-title', 'RCW Title 9: CRIMES AND PUNISHMENTS'),
  ('rcw-title-9a',    'RCW Title 9A — Washington Criminal Code',                                      'rcw-title', 'RCW Title 9A: WASHINGTON CRIMINAL CODE'),
  ('rcw-title-10',    'RCW Title 10 — Criminal Procedure',                                            'rcw-title', 'RCW Title 10: CRIMINAL PROCEDURE'),
  ('rcw-title-11',    'RCW Title 11 — Probate and Trust Law',                                         'rcw-title', 'RCW Title 11: PROBATE AND TRUST LAW'),
  ('rcw-title-12',    'RCW Title 12 — District Courts—Civil Procedure',                               'rcw-title', 'RCW Title 12: DISTRICT COURTS—CIVIL PROCEDURE'),
  ('rcw-title-13',    'RCW Title 13 — Juvenile Courts and Juvenile Offenders',                        'rcw-title', 'RCW Title 13: JUVENILE COURTS AND JUVENILE OFFENDERS'),
  ('rcw-title-14',    'RCW Title 14 — Aeronautics',                                                   'rcw-title', 'RCW Title 14: AERONAUTICS'),
  ('rcw-title-15',    'RCW Title 15 — Agriculture and Marketing',                                     'rcw-title', 'RCW Title 15: AGRICULTURE AND MARKETING'),
  ('rcw-title-16',    'RCW Title 16 — Animals and Livestock',                                         'rcw-title', 'RCW Title 16: ANIMALS AND LIVESTOCK'),
  ('rcw-title-17',    'RCW Title 17 — Weeds, Rodents, and Pests',                                     'rcw-title', 'RCW Title 17: WEEDS, RODENTS, AND PESTS'),
  ('rcw-title-18',    'RCW Title 18 — Businesses and Professions',                                    'rcw-title', 'RCW Title 18: BUSINESSES AND PROFESSIONS'),
  ('rcw-title-19',    'RCW Title 19 — Business Regulations—Miscellaneous',                            'rcw-title', 'RCW Title 19: BUSINESS REGULATIONS—MISCELLANEOUS'),
  ('rcw-title-20',    'RCW Title 20 — Commission Merchants—Agricultural Products',                    'rcw-title', 'RCW Title 20: COMMISSION MERCHANTS—AGRICULTURAL PRODUCTS'),
  ('rcw-title-21',    'RCW Title 21 — Securities and Investments',                                    'rcw-title', 'RCW Title 21: SECURITIES AND INVESTMENTS'),
  ('rcw-title-22',    'RCW Title 22 — Warehousing and Deposits',                                      'rcw-title', 'RCW Title 22: WAREHOUSING AND DEPOSITS'),
  ('rcw-title-23',    'RCW Title 23 — Corporations and Associations (Profit)',                        'rcw-title', 'RCW Title 23: CORPORATIONS AND ASSOCIATIONS (PROFIT) (Business Corporation Act: See Title 23B RCW)'),
  ('rcw-title-23b',   'RCW Title 23B — Washington Business Corporation Act',                          'rcw-title', 'RCW Title 23B: WASHINGTON BUSINESS CORPORATION ACT'),
  ('rcw-title-24',    'RCW Title 24 — Corporations and Associations (Nonprofit)',                     'rcw-title', 'RCW Title 24: CORPORATIONS AND ASSOCIATIONS (NONPROFIT)'),
  ('rcw-title-25',    'RCW Title 25 — Partnerships',                                                  'rcw-title', 'RCW Title 25: PARTNERSHIPS'),
  ('rcw-title-26',    'RCW Title 26 — Domestic Relations',                                            'rcw-title', 'RCW Title 26: DOMESTIC RELATIONS'),
  ('rcw-title-27',    'RCW Title 27 — Libraries, Museums, and Historical Activities',                 'rcw-title', 'RCW Title 27: LIBRARIES, MUSEUMS, AND HISTORICAL ACTIVITIES'),
  ('rcw-title-28a',   'RCW Title 28A — Common School Provisions',                                     'rcw-title', 'RCW Title 28A: COMMON SCHOOL PROVISIONS'),
  ('rcw-title-28b',   'RCW Title 28B — Higher Education',                                             'rcw-title', 'RCW Title 28B: HIGHER EDUCATION'),
  ('rcw-title-28c',   'RCW Title 28C — Vocational Education',                                         'rcw-title', 'RCW Title 28C: VOCATIONAL EDUCATION'),
  ('rcw-title-29a',   'RCW Title 29A — Elections',                                                    'rcw-title', 'RCW Title 29A: ELECTIONS'),
  ('rcw-title-29b',   'RCW Title 29B — Campaign Disclosure and Contribution',                         'rcw-title', 'RCW Title 29B: CAMPAIGN DISCLOSURE AND CONTRIBUTION'),
  ('rcw-title-30a',   'RCW Title 30A — Washington Commercial Bank Act',                               'rcw-title', 'RCW Title 30A: WASHINGTON COMMERCIAL BANK ACT'),
  ('rcw-title-30b',   'RCW Title 30B — Washington Trust Institutions Act',                            'rcw-title', 'RCW Title 30B: WASHINGTON TRUST INSTITUTIONS ACT'),
  ('rcw-title-31',    'RCW Title 31 — Miscellaneous Loan Agencies',                                   'rcw-title', 'RCW Title 31: MISCELLANEOUS LOAN AGENCIES'),
  ('rcw-title-32',    'RCW Title 32 — Washington Savings Bank Act',                                   'rcw-title', 'RCW Title 32: WASHINGTON SAVINGS BANK ACT'),
  ('rcw-title-33',    'RCW Title 33 — Washington Savings Association Act',                            'rcw-title', 'RCW Title 33: WASHINGTON SAVINGS ASSOCIATION ACT'),
  ('rcw-title-34',    'RCW Title 34 — Administrative Law',                                            'rcw-title', 'RCW Title 34: ADMINISTRATIVE LAW'),
  ('rcw-title-35',    'RCW Title 35 — Cities and Towns',                                              'rcw-title', 'RCW Title 35: CITIES AND TOWNS'),
  ('rcw-title-35a',   'RCW Title 35A — Optional Municipal Code',                                      'rcw-title', 'RCW Title 35A: OPTIONAL MUNICIPAL CODE'),
  ('rcw-title-36',    'RCW Title 36 — Counties',                                                      'rcw-title', 'RCW Title 36: COUNTIES'),
  ('rcw-title-37',    'RCW Title 37 — Federal Areas—Indians',                                         'rcw-title', 'RCW Title 37: FEDERAL AREAS—INDIANS'),
  ('rcw-title-38',    'RCW Title 38 — Militia and Military Affairs',                                  'rcw-title', 'RCW Title 38: MILITIA AND MILITARY AFFAIRS'),
  ('rcw-title-39',    'RCW Title 39 — Public Contracts and Indebtedness',                             'rcw-title', 'RCW Title 39: PUBLIC CONTRACTS AND INDEBTEDNESS'),
  ('rcw-title-40',    'RCW Title 40 — Public Documents, Records, and Publications',                   'rcw-title', 'RCW Title 40: PUBLIC DOCUMENTS, RECORDS, AND PUBLICATIONS'),
  ('rcw-title-41',    'RCW Title 41 — Public Employment, Civil Service, and Pensions',                'rcw-title', 'RCW Title 41: PUBLIC EMPLOYMENT, CIVIL SERVICE, AND PENSIONS'),
  ('rcw-title-42',    'RCW Title 42 — Public Officers and Agencies',                                  'rcw-title', 'RCW Title 42: PUBLIC OFFICERS AND AGENCIES'),
  ('rcw-title-43',    'RCW Title 43 — State Government—Executive',                                    'rcw-title', 'RCW Title 43: STATE GOVERNMENT—EXECUTIVE'),
  ('rcw-title-44',    'RCW Title 44 — State Government—Legislative',                                  'rcw-title', 'RCW Title 44: STATE GOVERNMENT—LEGISLATIVE'),
  ('rcw-title-46',    'RCW Title 46 — Motor Vehicles',                                                'rcw-title', 'RCW Title 46: MOTOR VEHICLES'),
  ('rcw-title-47',    'RCW Title 47 — Public Highways and Transportation',                            'rcw-title', 'RCW Title 47: PUBLIC HIGHWAYS AND TRANSPORTATION'),
  ('rcw-title-48',    'RCW Title 48 — Insurance',                                                     'rcw-title', 'RCW Title 48: INSURANCE'),
  ('rcw-title-49',    'RCW Title 49 — Labor Regulations',                                             'rcw-title', 'RCW Title 49: LABOR REGULATIONS'),
  ('rcw-title-50',    'RCW Title 50 — Unemployment Compensation',                                     'rcw-title', 'RCW Title 50: UNEMPLOYMENT COMPENSATION'),
  ('rcw-title-50a',   'RCW Title 50A — Family and Medical Leave',                                     'rcw-title', 'RCW Title 50A: FAMILY AND MEDICAL LEAVE'),
  ('rcw-title-50b',   'RCW Title 50B — Long-Term Care',                                               'rcw-title', 'RCW Title 50B: LONG-TERM CARE'),
  ('rcw-title-51',    'RCW Title 51 — Industrial Insurance',                                          'rcw-title', 'RCW Title 51: INDUSTRIAL INSURANCE'),
  ('rcw-title-52',    'RCW Title 52 — Fire Protection Districts',                                     'rcw-title', 'RCW Title 52: FIRE PROTECTION DISTRICTS'),
  ('rcw-title-53',    'RCW Title 53 — Port Districts',                                                'rcw-title', 'RCW Title 53: PORT DISTRICTS'),
  ('rcw-title-54',    'RCW Title 54 — Public Utility Districts',                                      'rcw-title', 'RCW Title 54: PUBLIC UTILITY DISTRICTS'),
  ('rcw-title-55',    'RCW Title 55 — Sanitary Districts',                                            'rcw-title', 'RCW Title 55: SANITARY DISTRICTS'),
  ('rcw-title-57',    'RCW Title 57 — Water-Sewer Districts',                                         'rcw-title', 'RCW Title 57: WATER-SEWER DISTRICTS'),
  ('rcw-title-58',    'RCW Title 58 — Boundaries and Plats',                                          'rcw-title', 'RCW Title 58: BOUNDARIES AND PLATS'),
  ('rcw-title-59',    'RCW Title 59 — Landlord and Tenant',                                           'rcw-title', 'RCW Title 59: LANDLORD AND TENANT'),
  ('rcw-title-60',    'RCW Title 60 — Liens',                                                         'rcw-title', 'RCW Title 60: LIENS'),
  ('rcw-title-61',    'RCW Title 61 — Mortgages, Deeds of Trust, and Real Estate Contracts',          'rcw-title', 'RCW Title 61: MORTGAGES, DEEDS OF TRUST, AND REAL ESTATE CONTRACTS'),
  ('rcw-title-62a',   'RCW Title 62A — Uniform Commercial Code',                                      'rcw-title', 'RCW Title 62A: UNIFORM COMMERCIAL CODE'),
  ('rcw-title-63',    'RCW Title 63 — Personal Property',                                             'rcw-title', 'RCW Title 63: PERSONAL PROPERTY'),
  ('rcw-title-64',    'RCW Title 64 — Real Property and Conveyances',                                 'rcw-title', 'RCW Title 64: REAL PROPERTY AND CONVEYANCES'),
  ('rcw-title-65',    'RCW Title 65 — Recording, Registration, and Legal Publication',                'rcw-title', 'RCW Title 65: RECORDING, REGISTRATION, AND LEGAL PUBLICATION'),
  ('rcw-title-66',    'RCW Title 66 — Alcoholic Beverage Control',                                    'rcw-title', 'RCW Title 66: ALCOHOLIC BEVERAGE CONTROL'),
  ('rcw-title-67',    'RCW Title 67 — Sports and Recreation—Convention Facilities',                   'rcw-title', 'RCW Title 67: SPORTS AND RECREATION—CONVENTION FACILITIES'),
  ('rcw-title-68',    'RCW Title 68 — Cemeteries, Morgues, and Human Remains',                        'rcw-title', 'RCW Title 68: CEMETERIES, MORGUES, AND HUMAN REMAINS'),
  ('rcw-title-69',    'RCW Title 69 — Food, Drugs, Cosmetics, and Poisons',                           'rcw-title', 'RCW Title 69: FOOD, DRUGS, COSMETICS, AND POISONS'),
  ('rcw-title-70',    'RCW Title 70 — Public Health and Safety',                                      'rcw-title', 'RCW Title 70: PUBLIC HEALTH AND SAFETY'),
  ('rcw-title-70a',   'RCW Title 70A — Environmental Health and Safety',                              'rcw-title', 'RCW Title 70A: ENVIRONMENTAL HEALTH AND SAFETY'),
  ('rcw-title-71',    'RCW Title 71 — Behavioral Health',                                             'rcw-title', 'RCW Title 71: BEHAVIORAL HEALTH'),
  ('rcw-title-71a',   'RCW Title 71A — Developmental Disabilities',                                   'rcw-title', 'RCW Title 71A: DEVELOPMENTAL DISABILITIES'),
  ('rcw-title-72',    'RCW Title 72 — State Institutions',                                            'rcw-title', 'RCW Title 72: STATE INSTITUTIONS'),
  ('rcw-title-73',    'RCW Title 73 — Veterans and Veterans'' Affairs',                               'rcw-title', 'RCW Title 73: VETERANS AND VETERANS'' AFFAIRS'),
  ('rcw-title-74',    'RCW Title 74 — Public Assistance',                                             'rcw-title', 'RCW Title 74: PUBLIC ASSISTANCE'),
  ('rcw-title-76',    'RCW Title 76 — Forests and Forest Products',                                   'rcw-title', 'RCW Title 76: FORESTS AND FOREST PRODUCTS'),
  ('rcw-title-77',    'RCW Title 77 — Fish and Wildlife',                                             'rcw-title', 'RCW Title 77: FISH AND WILDLIFE'),
  ('rcw-title-78',    'RCW Title 78 — Mines, Minerals, and Petroleum',                                'rcw-title', 'RCW Title 78: MINES, MINERALS, AND PETROLEUM'),
  ('rcw-title-79',    'RCW Title 79 — Public Lands',                                                  'rcw-title', 'RCW Title 79: PUBLIC LANDS'),
  ('rcw-title-79a',   'RCW Title 79A — Public Recreational Lands',                                    'rcw-title', 'RCW Title 79A: PUBLIC RECREATIONAL LANDS'),
  ('rcw-title-80',    'RCW Title 80 — Public Utilities',                                              'rcw-title', 'RCW Title 80: PUBLIC UTILITIES'),
  ('rcw-title-81',    'RCW Title 81 — Transportation',                                                'rcw-title', 'RCW Title 81: TRANSPORTATION'),
  ('rcw-title-82',    'RCW Title 82 — Excise Taxes',                                                  'rcw-title', 'RCW Title 82: EXCISE TAXES'),
  ('rcw-title-83',    'RCW Title 83 — Estate Taxation',                                               'rcw-title', 'RCW Title 83: ESTATE TAXATION'),
  ('rcw-title-84',    'RCW Title 84 — Property Taxes',                                                'rcw-title', 'RCW Title 84: PROPERTY TAXES'),
  ('rcw-title-85',    'RCW Title 85 — Diking and Drainage',                                           'rcw-title', 'RCW Title 85: DIKING AND DRAINAGE'),
  ('rcw-title-86',    'RCW Title 86 — Flood Control',                                                 'rcw-title', 'RCW Title 86: FLOOD CONTROL'),
  ('rcw-title-87',    'RCW Title 87 — Irrigation',                                                    'rcw-title', 'RCW Title 87: IRRIGATION'),
  ('rcw-title-88',    'RCW Title 88 — Navigation and Harbor Improvements',                            'rcw-title', 'RCW Title 88: NAVIGATION AND HARBOR IMPROVEMENTS'),
  ('rcw-title-89',    'RCW Title 89 — Reclamation, Soil Conservation, and Land Settlement',           'rcw-title', 'RCW Title 89: RECLAMATION, SOIL CONSERVATION, AND LAND SETTLEMENT'),
  ('rcw-title-90',    'RCW Title 90 — Water Rights—Environment',                                      'rcw-title', 'RCW Title 90: WATER RIGHTS—ENVIRONMENT'),
  ('rcw-title-91',    'RCW Title 91 — Waterways',                                                     'rcw-title', 'RCW Title 91: WATERWAYS')
ON CONFLICT (slug) DO NOTHING;


-- ============================================================================
-- §LEGACY-MIGRATION  (only AFTER §3c creates target tags)
-- ============================================================================
-- Migrates 4 wlad + 1 pra associations to the newly-created legal-framework
-- counterparts, then drops the legacy NULL-category tag rows. The other 5
-- NULL-category legacy tags (galvin, galvin-dual-role, snohomish-county-
-- legal-services, legal-automation, athena-paralegal) are untouched per
-- operator decision (deferred to a separate tag-hygiene task).

-- Migrate legacy wlad (id=242) → new legal-framework:wlad
INSERT INTO core.document_tags (document_id, tag_id)
SELECT dt.document_id,
       (SELECT id FROM core.tags WHERE category='legal-framework' AND slug='wlad')
FROM core.document_tags dt
WHERE dt.tag_id = 242
ON CONFLICT (document_id, tag_id) DO NOTHING;

-- Migrate legacy pra (id=606) → new legal-framework:pra
INSERT INTO core.document_tags (document_id, tag_id)
SELECT dt.document_id,
       (SELECT id FROM core.tags WHERE category='legal-framework' AND slug='pra')
FROM core.document_tags dt
WHERE dt.tag_id = 606
ON CONFLICT (document_id, tag_id) DO NOTHING;

-- Drop legacy associations (5 join rows: 4 wlad + 1 pra)
DELETE FROM core.document_tags WHERE tag_id IN (242, 606);

-- Drop now-orphaned legacy tag rows
DELETE FROM core.tags WHERE id IN (242, 606);


-- ============================================================================
-- §4  USC RETROACTIVE TAGGING — apply `code-jurisdiction:federal-usc` to all
--                                11,678 existing USC documents
-- ============================================================================
-- Anchor: every USC doc carries the existing `usc-meta:usc` tag. Use it as
-- the predicate selector. ON CONFLICT against the (document_id, tag_id) PK
-- makes this idempotent.

INSERT INTO core.document_tags (document_id, tag_id)
SELECT
  dt.document_id,
  (SELECT id FROM core.tags
    WHERE category='code-jurisdiction' AND slug='federal-usc') AS tag_id
FROM core.document_tags dt
JOIN core.tags t ON t.id = dt.tag_id
WHERE t.category='usc-meta' AND t.slug='usc'
ON CONFLICT (document_id, tag_id) DO NOTHING;


-- ============================================================================
-- §POST-APPLY GUARDS (raise EXCEPTION on mismatch — triggers rollback)
-- ============================================================================
-- Final sanity checks INSIDE the transaction. If any check fails, the entire
-- transaction rolls back and the database is unchanged.
--
-- Note: the slug check below uses the bare slug 'federal-usc' (NOT the
-- category-prefixed form) because that's how §3a inserts it. Slug is unique
-- globally; category is a separate column. Pairing both in the WHERE is the
-- canonical lookup pattern.

DO $$
DECLARE
  wlad_migrated         INTEGER;
  pra_migrated          INTEGER;
  legacy_tag_rows_left  INTEGER;
  legacy_join_rows_left INTEGER;
  usc_tagged            INTEGER;
  rcw_tables_present    INTEGER;
  new_tag_count         INTEGER;
BEGIN
  -- Post.1 All 4 originally-wlad-tagged docs now carry legal-framework:wlad
  SELECT COUNT(*) INTO wlad_migrated FROM core.document_tags dt
  JOIN core.tags t ON t.id = dt.tag_id
  WHERE t.category='legal-framework' AND t.slug='wlad'
  AND dt.document_id IN (
    '228abe05-8607-4ed0-a432-c4f1e4ab3902',
    '319c0009-efa4-4dd1-90c6-5b8a28d506d3',
    '7c695a5f-b7db-490d-879a-a6fa47b0770b',
    '84cbd52d-95bd-4e6a-af6d-c21508936434'
  );
  IF wlad_migrated <> 4 THEN
    RAISE EXCEPTION 'Post-apply FAIL [Post.1]: WLAD migration count = %, expected 4. Rolling back.', wlad_migrated;
  END IF;

  -- Post.2 The single pra doc carries legal-framework:pra
  SELECT COUNT(*) INTO pra_migrated FROM core.document_tags dt
  JOIN core.tags t ON t.id = dt.tag_id
  WHERE t.category='legal-framework' AND t.slug='pra'
  AND dt.document_id = '228abe05-8607-4ed0-a432-c4f1e4ab3902';
  IF pra_migrated <> 1 THEN
    RAISE EXCEPTION 'Post-apply FAIL [Post.2]: PRA migration count = %, expected 1. Rolling back.', pra_migrated;
  END IF;

  -- Post.3 Legacy tag rows (id=242, id=606) are gone from core.tags
  SELECT COUNT(*) INTO legacy_tag_rows_left FROM core.tags WHERE id IN (242, 606);
  IF legacy_tag_rows_left <> 0 THEN
    RAISE EXCEPTION 'Post-apply FAIL [Post.3]: legacy tag rows still present in core.tags (count=%). Rolling back.', legacy_tag_rows_left;
  END IF;

  -- Post.4 Legacy join rows (tag_id=242, tag_id=606) are gone from core.document_tags
  SELECT COUNT(*) INTO legacy_join_rows_left FROM core.document_tags WHERE tag_id IN (242, 606);
  IF legacy_join_rows_left <> 0 THEN
    RAISE EXCEPTION 'Post-apply FAIL [Post.4]: legacy join rows still present in core.document_tags (count=%). Rolling back.', legacy_join_rows_left;
  END IF;

  -- Post.5 All 11,678 USC docs carry code-jurisdiction:federal-usc
  -- (note: WHERE pairs both category and slug — slug alone is globally unique
  -- but the pair is the canonical lookup form; same-row lookup either way)
  SELECT COUNT(*) INTO usc_tagged FROM core.document_tags dt
  JOIN core.tags t ON t.id = dt.tag_id
  WHERE t.category='code-jurisdiction' AND t.slug='federal-usc';
  IF usc_tagged <> 11678 THEN
    RAISE EXCEPTION 'Post-apply FAIL [Post.5]: USC retro-tag count = %, expected 11678. Rolling back.', usc_tagged;
  END IF;

  -- Post.6 All 7 rcw.* tables exist
  SELECT COUNT(*) INTO rcw_tables_present FROM information_schema.tables
    WHERE table_schema='rcw'
      AND table_name IN ('titles','chapters','sections','cross_references',
                          'section_history','section_notes','ingestion_runs');
  IF rcw_tables_present <> 7 THEN
    RAISE EXCEPTION 'Post-apply FAIL [Post.6]: rcw.* table count = %, expected 7. Rolling back.', rcw_tables_present;
  END IF;

  -- Post.7 New tag rows: 2 code-jurisdiction + 8 rcw-meta + 17 legal-framework
  --        (RCW additions, net of existing 28) + 100 rcw-title = 127 new rows
  --        in those four categories, minus the 2 legacy rows we removed = net
  --        addition of 125. We measure new total: existing 28 legal-framework
  --        - 0 (we didn't remove any in that category — wlad/pra were NULL-
  --        category) + 17 = 45 in legal-framework. Plus the 4 new categories
  --        with 2+8+100 = 110. Easier to count as a positive existence check:
  SELECT
    (SELECT COUNT(*) FROM core.tags WHERE category='code-jurisdiction')
    + (SELECT COUNT(*) FROM core.tags WHERE category='rcw-meta')
    + (SELECT COUNT(*) FROM core.tags WHERE category='rcw-title')
    INTO new_tag_count;
  IF new_tag_count <> 110 THEN
    RAISE EXCEPTION 'Post-apply FAIL [Post.7]: new tag categories total = %, expected 110 (2 code-jurisdiction + 8 rcw-meta + 100 rcw-title). Rolling back.', new_tag_count;
  END IF;

  RAISE NOTICE 'Post-apply guards: PASS (wlad migrated=4, pra migrated=1, legacy gone, USC tagged=11678, 7 rcw.* tables, 110 tag rows in new categories)';
END $$;


-- ============================================================================
-- COMMIT
-- ============================================================================
-- If we got here, all guards passed. COMMIT makes the changes durable.
-- If any guard above raised EXCEPTION, the transaction was already rolled back
-- by ON_ERROR_STOP and this COMMIT is skipped.

COMMIT;


-- ============================================================================
-- §5  POST-COMMIT VERIFICATION SELECTS
-- ============================================================================
-- These run AFTER the transaction commits, in autocommit mode. Their results
-- print to stdout for the operator to inspect. They are read-only and any
-- failure here does NOT roll back the apply (already committed).
--
-- Operator: paste the entire psql output (including these results) back to
-- the agent for parsing and Phase 2 authorization decision.

\echo '--- §5.1 rcw schema and 7 tables exist ---'
SELECT
  EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name='rcw')                                 AS rcw_schema,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='rcw' AND table_name='titles')          AS titles_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='rcw' AND table_name='chapters')        AS chapters_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='rcw' AND table_name='sections')        AS sections_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='rcw' AND table_name='cross_references') AS xref_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='rcw' AND table_name='section_history') AS history_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='rcw' AND table_name='section_notes')   AS notes_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='rcw' AND table_name='ingestion_runs')  AS runs_tbl;

\echo ''
\echo '--- §5.2 Tag pre-seeds inserted ---'
SELECT
  (SELECT COUNT(*) FROM core.tags WHERE category='code-jurisdiction')   AS code_jurisdiction_n,    -- expect 2
  (SELECT COUNT(*) FROM core.tags WHERE category='rcw-meta')            AS rcw_meta_n,             -- expect 8
  (SELECT COUNT(*) FROM core.tags WHERE category='rcw-title')           AS rcw_title_n,            -- expect 100
  (SELECT COUNT(*) FROM core.tags WHERE category='legal-framework')     AS legal_framework_total;  -- expect 28 + 17 = 45

\echo ''
\echo '--- §5.3 USC retroactive tagging count ---'
SELECT COUNT(*) AS usc_docs_with_code_jurisdiction
FROM core.document_tags dt
JOIN core.tags t ON t.id = dt.tag_id
WHERE t.category='code-jurisdiction' AND t.slug='federal-usc';
-- expect: 11678

\echo ''
\echo '--- §5.4 [Additional] Legacy tag rows are gone ---'
SELECT COUNT(*) AS should_be_zero FROM core.tags WHERE id IN (242, 606);
-- expect: 0

\echo ''
\echo '--- §5.5 [Additional] All 4 wlad-tagged docs have new legal-framework:wlad ---'
SELECT COUNT(*) AS should_be_4 FROM core.document_tags dt
JOIN core.tags t ON t.id = dt.tag_id
WHERE t.category='legal-framework' AND t.slug='wlad'
AND dt.document_id IN (
  '228abe05-8607-4ed0-a432-c4f1e4ab3902',
  '319c0009-efa4-4dd1-90c6-5b8a28d506d3',
  '7c695a5f-b7db-490d-879a-a6fa47b0770b',
  '84cbd52d-95bd-4e6a-af6d-c21508936434'
);
-- expect: 4

\echo ''
\echo '--- §5.6 [Additional] 228abe05 retains pra under new categorized tag ---'
SELECT COUNT(*) AS should_be_1 FROM core.document_tags dt
JOIN core.tags t ON t.id = dt.tag_id
WHERE t.category='legal-framework' AND t.slug='pra'
AND dt.document_id='228abe05-8607-4ed0-a432-c4f1e4ab3902';
-- expect: 1

\echo ''
\echo '--- §5.7 The non-colliding legacy tags are STILL PRESENT (deferred hygiene) ---'
SELECT t.id, t.name, COUNT(dt.document_id) AS docs_associated
FROM core.tags t
LEFT JOIN core.document_tags dt ON dt.tag_id = t.id
WHERE t.id IN (488, 597, 256, 340, 718)
GROUP BY t.id, t.name
ORDER BY t.id;
-- expect: 5 rows (galvin-dual-role, galvin, legal-automation, athena-paralegal, snohomish-county-legal-services)
-- with their original document association counts (1, 4, 2, 1, 1 respectively).

\echo ''
\echo '--- §5.8 Existing jurisdiction:wa:ada is untouched ---'
SELECT id, slug, name, category FROM core.tags
WHERE category='jurisdiction' AND slug='wa:ada';
-- expect: 1 row, exactly as it was before apply

\echo ''
\echo '=== END schema_apply.sql ==='
\echo 'Capture complete output and paste to agent for Phase 2 authorization.'

-- ============================================================================
-- END OF FILE
-- ============================================================================
