-- =============================================================================
-- WA Court Rules Phase 1 SCHEMA EXTENSION — STAGED FOR OPERATOR REVIEW
-- =============================================================================
-- Generated by:  WA Court Rules ingest agent
-- Generated at:  2026-04-30 (post Gate-2 architectural decision)
-- Operator:      William J. Nelson — apply via psql, not autonomously
-- Status:        STAGED — DO NOT APPLY without explicit operator authorization.
--
-- Purpose:
--   ALTER wa_court_rules.rules to support Option B handling of APR irregular
--   IDs (Regs, LP_REGS, LP_DIS_REGS, 15P) per Phase 3 Gate 2 architectural
--   decision. Adds parent_regulation_handle TEXT column with parallel CHECK
--   semantics to the existing parent_canon column for CJC, plus a defensive
--   mutual-exclusion CHECK and a partial index for reverse queries.
--
-- This script is atomic (single transaction). If any pre-flight or post-apply
-- guard fails, ON_ERROR_STOP triggers full ROLLBACK.
--
-- HOW TO APPLY (after operator authorizes):
--
--   psql "$DATABASE_URL" -f /opt/wdws/wa_court_rules_research/phase1_schema_extension.sql \
--     2>&1 | tee /opt/wdws/wa_court_rules_research/phase1_schema_extension_output.log
--
-- Expected behavior:
--   1. §0 pre-flight: parent_regulation_handle column doesn't exist yet,
--      no name-collision index, schema/tables intact, wa_court_rules.rules
--      empty (no premature ingest)
--   2. §1 ADD COLUMN parent_regulation_handle TEXT
--   3. §2 ADD CONSTRAINT chk_parent_regulation_handle_only_apr
--      (parallel to chk_parent_canon_only_cjc)
--   4. §3 ADD CONSTRAINT chk_at_most_one_parent_pointer
--      (defensive mutual-exclusion: rule cannot have both parent_canon AND
--      parent_regulation_handle non-NULL)
--   5. §4 CREATE INDEX idx_rules_parent_regulation_handle (partial,
--      WHERE parent_regulation_handle IS NOT NULL)
--   6. §5 COMMENT ON COLUMN documenting purpose + mutual exclusion
--   7. §POST: column exists, both new constraints landed, partial index
--      present, no rules rows orphaned (since table is empty)
--   8. §V: print verification SELECTs for operator review
--   9. COMMIT (or ROLLBACK on any failure)
--
-- Estimated wall time: under 2 sec. Pure DDL on an empty table.
-- =============================================================================

\set ON_ERROR_STOP on
\timing on

BEGIN;


-- =============================================================================
-- §0  PRE-EXECUTION GUARDS
-- =============================================================================

DO $$
DECLARE
  col_exists                 INTEGER;
  apr_check_exists           INTEGER;
  mutex_check_exists         INTEGER;
  partial_idx_exists         INTEGER;
  schema_present             INTEGER;
  rules_table_present        INTEGER;
  rules_row_count            INTEGER;
  parent_canon_check_present INTEGER;
BEGIN
  -- §0.1 wa_court_rules schema present
  SELECT COUNT(*) INTO schema_present
    FROM information_schema.schemata WHERE schema_name = 'wa_court_rules';
  IF schema_present <> 1 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.1]: wa_court_rules schema missing. Phase 1 apply did not run, or schema was dropped.';
  END IF;

  -- §0.2 wa_court_rules.rules table present
  SELECT COUNT(*) INTO rules_table_present
    FROM information_schema.tables
    WHERE table_schema = 'wa_court_rules' AND table_name = 'rules';
  IF rules_table_present <> 1 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.2]: wa_court_rules.rules table missing.';
  END IF;

  -- §0.3 Pre-existing chk_parent_canon_only_cjc present (we mirror its semantics)
  SELECT COUNT(*) INTO parent_canon_check_present
    FROM pg_constraint
    WHERE conname = 'chk_parent_canon_only_cjc'
      AND conrelid = 'wa_court_rules.rules'::regclass;
  IF parent_canon_check_present <> 1 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.3]: chk_parent_canon_only_cjc absent. Phase 1 apply incomplete or modified.';
  END IF;

  -- §0.4 parent_regulation_handle column does NOT yet exist
  SELECT COUNT(*) INTO col_exists
    FROM information_schema.columns
    WHERE table_schema = 'wa_court_rules'
      AND table_name = 'rules'
      AND column_name = 'parent_regulation_handle';
  IF col_exists <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.4]: parent_regulation_handle column already exists. Extension was already applied or partial-applied — investigate.';
  END IF;

  -- §0.5 Neither new CHECK constraint exists yet
  SELECT COUNT(*) INTO apr_check_exists
    FROM pg_constraint
    WHERE conname = 'chk_parent_regulation_handle_only_apr'
      AND conrelid = 'wa_court_rules.rules'::regclass;
  IF apr_check_exists <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.5a]: chk_parent_regulation_handle_only_apr already exists.';
  END IF;

  SELECT COUNT(*) INTO mutex_check_exists
    FROM pg_constraint
    WHERE conname = 'chk_at_most_one_parent_pointer'
      AND conrelid = 'wa_court_rules.rules'::regclass;
  IF mutex_check_exists <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.5b]: chk_at_most_one_parent_pointer already exists.';
  END IF;

  -- §0.6 Partial index does NOT yet exist
  SELECT COUNT(*) INTO partial_idx_exists
    FROM pg_indexes
    WHERE schemaname = 'wa_court_rules'
      AND indexname = 'idx_rules_parent_regulation_handle';
  IF partial_idx_exists <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.6]: idx_rules_parent_regulation_handle already exists.';
  END IF;

  -- §0.7 wa_court_rules.rules is empty (no premature ingest, so the new
  --      column starts NULL on every (zero) existing row)
  SELECT COUNT(*) INTO rules_row_count FROM wa_court_rules.rules;
  IF rules_row_count <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.7]: wa_court_rules.rules has % rows; expected 0 (Phase 4 ingest has not run yet). Halt — investigate before applying ALTER.', rules_row_count;
  END IF;

  RAISE NOTICE 'Pre-flight: PASS — schema + rules table present; chk_parent_canon_only_cjc baseline present; parent_regulation_handle column absent; both new CHECKs absent; partial index absent; wa_court_rules.rules empty (0 rows)';
END $$;


-- =============================================================================
-- §1  ADD COLUMN parent_regulation_handle
-- =============================================================================

ALTER TABLE wa_court_rules.rules
  ADD COLUMN parent_regulation_handle TEXT;


-- =============================================================================
-- §2  PARALLEL CHECK to chk_parent_canon_only_cjc
-- =============================================================================
-- Restricts parent_regulation_handle to APR rule_set_code only. Mirrors the
-- existing chk_parent_canon_only_cjc constraint that restricts parent_canon
-- to CJC. NULL parent_regulation_handle is allowed for all rule sets;
-- non-NULL is allowed only when rule_set_code='APR'.

ALTER TABLE wa_court_rules.rules
  ADD CONSTRAINT chk_parent_regulation_handle_only_apr
  CHECK (parent_regulation_handle IS NULL OR rule_set_code = 'APR');


-- =============================================================================
-- §3  DEFENSIVE MUTUAL EXCLUSION
-- =============================================================================
-- A rule cannot have both parent_canon (CJC inner-rule) AND
-- parent_regulation_handle (APR irregular-handle child) populated. In normal
-- operation this is enforced by the rule_set_code-based CHECKs above
-- (parent_canon requires CJC; parent_regulation_handle requires APR; rule_set_code
-- is single-valued). This third CHECK is a structurally-different audit
-- channel — it defends against schema misuse if rule_set_code somehow becomes
-- inconsistent. Cheap defense paralleling other §K-style structurally-different
-- audits (chk_range_self_consistency, chk_comment_consistency, etc.).

ALTER TABLE wa_court_rules.rules
  ADD CONSTRAINT chk_at_most_one_parent_pointer
  CHECK (NOT (parent_canon IS NOT NULL AND parent_regulation_handle IS NOT NULL));


-- =============================================================================
-- §4  PARTIAL INDEX for reverse queries
-- =============================================================================
-- For "show me all child rows under parent handle X" queries (Phase 6
-- retrieval pattern). Partial index keeps it small — only ~32 rows total
-- across the four APR irregular handles will populate this column.

CREATE INDEX idx_rules_parent_regulation_handle
  ON wa_court_rules.rules (parent_regulation_handle)
  WHERE parent_regulation_handle IS NOT NULL;


-- =============================================================================
-- §5  COMMENT ON COLUMN documenting purpose
-- =============================================================================

COMMENT ON COLUMN wa_court_rules.rules.parent_regulation_handle IS
  'For APR irregular-handle rules (Regs, LP_REGS, LP_DIS_REGS): the parent '
  'handle this row belongs to. NULL for non-APR rules and for APR numbered '
  'rules. Mutually exclusive with parent_canon (enforced by '
  'chk_at_most_one_parent_pointer). Set:'
  '  parent_regulation_handle=''Regs''        for sub-rows under APR Regs '
  '(Continuing Legal Education Board regulations); '
  '  parent_regulation_handle=''LP_REGS''     for sub-rows under APR LP_REGS '
  '(Limited Practice Board regulations appendix); '
  '  parent_regulation_handle=''LP_DIS_REGS'' for sub-rows under APR LP_DIS_REGS '
  '(Limited Practice Officer disciplinary regulations); '
  '  rule_number=''15P'' is handled via the main numbered-rule path '
  '(15P matches \\d+[A-Z]? in the citation regex); no parent_regulation_handle '
  'needed for APR 15P sub-regulations because the handle is encoded in the '
  'rule_number itself.';


-- =============================================================================
-- §POST  POST-APPLY GUARDS
-- =============================================================================

DO $$
DECLARE
  col_exists                 INTEGER;
  apr_check_exists           INTEGER;
  mutex_check_exists         INTEGER;
  partial_idx_exists         INTEGER;
  apr_check_def              TEXT;
  mutex_check_def            TEXT;
BEGIN
  -- §POST.1 column landed
  SELECT COUNT(*) INTO col_exists
    FROM information_schema.columns
    WHERE table_schema = 'wa_court_rules'
      AND table_name = 'rules'
      AND column_name = 'parent_regulation_handle';
  IF col_exists <> 1 THEN
    RAISE EXCEPTION 'Post-apply FAIL [§POST.1]: parent_regulation_handle column missing.';
  END IF;

  -- §POST.2 chk_parent_regulation_handle_only_apr present + correct
  SELECT COUNT(*), MAX(pg_get_constraintdef(oid))
    INTO apr_check_exists, apr_check_def
    FROM pg_constraint
    WHERE conname = 'chk_parent_regulation_handle_only_apr'
      AND conrelid = 'wa_court_rules.rules'::regclass;
  IF apr_check_exists <> 1 THEN
    RAISE EXCEPTION 'Post-apply FAIL [§POST.2a]: chk_parent_regulation_handle_only_apr missing.';
  END IF;
  IF apr_check_def NOT LIKE '%parent_regulation_handle%' OR apr_check_def NOT LIKE '%APR%' THEN
    RAISE EXCEPTION 'Post-apply FAIL [§POST.2b]: chk_parent_regulation_handle_only_apr definition unexpected: %', apr_check_def;
  END IF;

  -- §POST.3 chk_at_most_one_parent_pointer present + correct
  SELECT COUNT(*), MAX(pg_get_constraintdef(oid))
    INTO mutex_check_exists, mutex_check_def
    FROM pg_constraint
    WHERE conname = 'chk_at_most_one_parent_pointer'
      AND conrelid = 'wa_court_rules.rules'::regclass;
  IF mutex_check_exists <> 1 THEN
    RAISE EXCEPTION 'Post-apply FAIL [§POST.3a]: chk_at_most_one_parent_pointer missing.';
  END IF;
  IF mutex_check_def NOT LIKE '%parent_canon%' OR mutex_check_def NOT LIKE '%parent_regulation_handle%' THEN
    RAISE EXCEPTION 'Post-apply FAIL [§POST.3b]: chk_at_most_one_parent_pointer definition unexpected: %', mutex_check_def;
  END IF;

  -- §POST.4 partial index present
  SELECT COUNT(*) INTO partial_idx_exists
    FROM pg_indexes
    WHERE schemaname = 'wa_court_rules'
      AND indexname = 'idx_rules_parent_regulation_handle';
  IF partial_idx_exists <> 1 THEN
    RAISE EXCEPTION 'Post-apply FAIL [§POST.4]: idx_rules_parent_regulation_handle missing.';
  END IF;

  RAISE NOTICE 'Post-apply: PASS — parent_regulation_handle column added; chk_parent_regulation_handle_only_apr + chk_at_most_one_parent_pointer landed; partial index present';
END $$;


-- =============================================================================
-- §V  VERIFICATION SELECTs
-- =============================================================================

\echo ''
\echo '=== §V.1 New column on wa_court_rules.rules ==='
SELECT column_name, data_type, is_nullable, col_description('wa_court_rules.rules'::regclass, ordinal_position) AS comment_excerpt
  FROM information_schema.columns
  WHERE table_schema = 'wa_court_rules'
    AND table_name = 'rules'
    AND column_name IN ('parent_canon', 'parent_regulation_handle')
  ORDER BY column_name;

\echo ''
\echo '=== §V.2 New + parallel CHECK constraints on wa_court_rules.rules ==='
SELECT conname AS constraint_name, pg_get_constraintdef(oid) AS definition
  FROM pg_constraint
  WHERE conrelid = 'wa_court_rules.rules'::regclass
    AND contype = 'c'
    AND conname IN ('chk_parent_canon_only_cjc',
                    'chk_parent_regulation_handle_only_apr',
                    'chk_at_most_one_parent_pointer')
  ORDER BY conname;

\echo ''
\echo '=== §V.3 Indexes on wa_court_rules.rules ==='
SELECT indexname, indexdef
  FROM pg_indexes
  WHERE schemaname = 'wa_court_rules'
    AND tablename = 'rules'
    AND indexname IN ('idx_rules_parent_canon_partial',
                      'idx_rules_parent_regulation_handle')
  ORDER BY indexname;


COMMIT;

\echo ''
\echo '=== Phase 1 schema extension: COMPLETE ==='
\echo 'Phase 3 parser build can now begin per kickoff §6 boundary.'
