-- =============================================================================
-- WAC Phase 1 Schema Apply — TRANSACTIONAL
-- =============================================================================
-- Generated by:  Athena WAC-Ingest agent (autonomous Phase 1 staging)
-- Generated at:  2026-04-30
-- Operator:      William J. Nelson — apply via psql, not autonomously
-- Status:        APPLY-READY — atomic single-transaction migration
--
-- Pre-execution requirements:
--   - PostgreSQL 17+ with pgvector extension loaded
--   - core.tags, core.documents, core.document_tags, usc.*, rcw.* schemas exist
--   - session_preload_libraries='vector' active (verified at OS level)
--
-- This script is atomic. Either the entire transaction commits or nothing
-- changes. If any pre-flight guard or post-apply guard fails, the transaction
-- is automatically ROLLed BACK by ON_ERROR_STOP / RAISE EXCEPTION.
--
-- Companion documents:
--   /opt/wdws/wac_research/wac_source_findings.md
--   /opt/wdws/wac_research/authority_chain_design.md
--   /opt/wdws/wac_research/litigation_priority_addendum.md
--   /opt/wdws/wac_research/phase0_cumulative_report.md
--   /opt/wdws/wac_research/schema_design.sql      (review-only; this file
--                                                   supersedes it for apply)
-- =============================================================================
--
-- HOW TO APPLY (operator instructions):
--
--   psql "$DATABASE_URL" -f /opt/wdws/wac_research/schema_apply.sql
--
-- Expected behavior:
--   1. §0 pre-flight guards print "PASS" NOTICE or RAISE EXCEPTION
--      (includes §0.7 — verifies 0 rows of 'wac' short form before harmonize)
--   2. §HARMONIZE drops + recreates rcw.cross_references CHECK enum
--   3. §1 schema + §2 indexes + §3 tag inserts execute
--   4. §POST-APPLY guards print "PASS" NOTICE or RAISE EXCEPTION
--      (§POST.9 verifies BOTH cross_refs CHECK enums use 'state-wa-wac'
--       and neither retains short-form 'wac')
--   5. COMMIT succeeds OR full ROLLBACK on any failure
--   6. §VERIFICATION SELECTs print to stdout for operator review
--      (§V.6 shows harmonized CHECK definitions for both tables)
--
-- Capture entire psql output (stdout + stderr) and paste back to the agent
-- for parsing and Phase 2 authorization decision.
--
-- Estimated wall time: under 10 seconds. No large UPDATEs in this migration
-- (no retroactive tagging — USC/RCW already carry code-jurisdiction tags;
-- §3 tag inserts are 20 rows total; §HARMONIZE is metadata-only DDL on a
-- table where 0 rows use the to-be-removed enum value).
-- =============================================================================

\set ON_ERROR_STOP on
\timing on

BEGIN;


-- =============================================================================
-- §0  PRE-EXECUTION GUARDS (raise EXCEPTION on mismatch — triggers rollback)
-- =============================================================================
-- Confirms the live schema is in the state staging design assumed at
-- 2026-04-30. Any drift halts the transaction before any writes.

DO $$
DECLARE
  wac_schema_exists    INTEGER;
  collision_count      INTEGER;
  wac_meta_pre         INTEGER;
  wac_title_pre        INTEGER;
  partial_idx_present  INTEGER;
  rcw_section_count    INTEGER;
  usc_tag_count        INTEGER;
  rcw_tag_count        INTEGER;
  cj_count             INTEGER;
  wac_short_count      INTEGER;
BEGIN
  -- §0.1 wac schema does not yet exist
  SELECT COUNT(*) INTO wac_schema_exists FROM information_schema.schemata WHERE schema_name='wac';
  IF wac_schema_exists <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.1]: wac schema already exists. Halt — investigate state before retry.';
  END IF;

  -- §0.2 None of the proposed slugs collide
  SELECT COUNT(*) INTO collision_count FROM core.tags
    WHERE slug IN (
      'state-wa-wac',
      'wac','state-regulation',
      'wac-repealed','wac-recodified','wac-decodified',
      'wac-expired','wac-reserved','wac-suspended',
      'wlad-enforcement-wac','bii-regulations-wac',
      'dshs-wac','dcyf-wac','hca-wac','doh-wac',
      'civil-service-wac','employment-security-wac',
      'licensing-wac','revenue-wac','pra-regulations-wac'
    );
  IF collision_count <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.2]: % proposed slug(s) already exist. Halt — investigate before retry.', collision_count;
  END IF;

  -- §0.3 wac-meta and wac-title categories empty (lazy-populated)
  SELECT COUNT(*) INTO wac_meta_pre  FROM core.tags WHERE category='wac-meta';
  IF wac_meta_pre <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.3a]: wac-meta category has % rows, expected 0. Halt.', wac_meta_pre;
  END IF;
  SELECT COUNT(*) INTO wac_title_pre FROM core.tags WHERE category='wac-title';
  IF wac_title_pre <> 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.3b]: wac-title category has % rows, expected 0 (lazy-populated). Halt.', wac_title_pre;
  END IF;

  -- §0.4 Existing partial unique index covers WAC source_path automatically
  SELECT COUNT(*) INTO partial_idx_present FROM pg_indexes
    WHERE schemaname='core' AND indexname='uniq_documents_usc_source';
  IF partial_idx_present <> 1 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.4]: uniq_documents_usc_source partial unique index missing. Halt.';
  END IF;

  -- §0.5 RCW + USC corpora intact (count snapshots — ensures we did not lose data
  --      since 2026-04-30 introspection)
  SELECT COUNT(*) INTO rcw_section_count FROM rcw.sections;
  IF rcw_section_count <> 51764 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.5a]: rcw.sections has % rows, expected 51,764. Halt.', rcw_section_count;
  END IF;

  SELECT COUNT(*) INTO usc_tag_count FROM core.document_tags dt
    JOIN core.tags t ON t.id=dt.tag_id
    WHERE t.category='code-jurisdiction' AND t.slug='federal-usc';
  IF usc_tag_count <> 11678 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.5b]: USC code-jurisdiction tag count is %, expected 11,678. Halt.', usc_tag_count;
  END IF;

  SELECT COUNT(*) INTO rcw_tag_count FROM core.document_tags dt
    JOIN core.tags t ON t.id=dt.tag_id
    WHERE t.category='code-jurisdiction' AND t.slug='state-wa-rcw';
  IF rcw_tag_count <> 51764 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.5c]: RCW code-jurisdiction tag count is %, expected 51,764. Halt.', rcw_tag_count;
  END IF;

  -- §0.6 Existing code-jurisdiction tags present and intact
  SELECT COUNT(*) INTO cj_count FROM core.tags
    WHERE category='code-jurisdiction' AND slug IN ('federal-usc','state-wa-rcw');
  IF cj_count <> 2 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.6]: code-jurisdiction has % of expected 2 baseline rows. Halt.', cj_count;
  END IF;

  -- §0.7 Harmonization pre-flight: 0 existing rows in rcw.cross_references
  --      use the short form 'wac'. Drift here would mean someone populated
  --      'wac' rows since the 2026-04-30 introspection — halt before
  --      DROP/RECREATE in §HARMONIZE would fail with constraint violation.
  SELECT COUNT(*) INTO wac_short_count FROM rcw.cross_references
    WHERE target_jurisdiction = 'wac';
  IF wac_short_count > 0 THEN
    RAISE EXCEPTION 'Pre-flight FAIL [§0.7]: % existing rcw.cross_references rows use short-form ''wac''. Migrate values before harmonization.', wac_short_count;
  END IF;

  RAISE NOTICE 'Pre-flight guards: PASS (no wac schema; 0 slug collisions; partial idx present; RCW=% USC=%; 0 rows use ''wac'' short form — harmonization is free)',
               rcw_section_count, usc_tag_count;
END $$;


-- =============================================================================
-- §HARMONIZE  Cross-references CHECK enum harmonization
-- =============================================================================
-- Per operator architectural correction 2026-04-30: harmonize the
-- target_jurisdiction CHECK enum on rcw.cross_references to use slug-aligned
-- 'state-wa-wac' instead of forward-looking placeholder 'wac'. ZERO existing
-- rows use 'wac' (verified §0.7 above), so this is a free DDL operation.
-- Same transaction as wac.* schema creation — atomic, rolls back if any
-- subsequent step fails.

ALTER TABLE rcw.cross_references DROP CONSTRAINT chk_target_jurisdiction;
ALTER TABLE rcw.cross_references ADD CONSTRAINT chk_target_jurisdiction CHECK (
  target_jurisdiction IN (
    'state-wa-rcw', 'federal-usc', 'state-wa-wac',
    'cfr', 'wa-court-rule', 'session-law', 'wa-constitution'
  )
);
COMMENT ON CONSTRAINT chk_target_jurisdiction ON rcw.cross_references IS
  'Slug-aligned for code-jurisdiction values: federal-usc, state-wa-rcw, '
  'state-wa-wac all match their core.tags slugs. Other enum values await '
  'harmonization when their respective corpora are scoped. Harmonized 2026-04-30 '
  'as part of WAC Phase 1 schema apply (zero existing rows used pre-existing '
  '''wac'' short form).';


-- =============================================================================
-- §1  WAC SCHEMA + TABLES
-- =============================================================================

CREATE SCHEMA wac;
COMMENT ON SCHEMA wac IS
  'Washington Administrative Code — state administrative regulations parallel '
  'to rcw.* and usc.*. Phase 4 ingest writes here; Phase 6 retrieval reads via '
  'core.documents/document_chunks (FK from wac.sections.document_id). Authority '
  'chain to rcw.* via wac.authority_chain join table. Designed 2026-04-30; see '
  '/opt/wdws/wac_research/schema_design.sql.';


-- §1.1 wac.titles
CREATE TABLE wac.titles (
    title_number      TEXT PRIMARY KEY,
    title_name        TEXT NOT NULL,
    agency_name       TEXT,
    publication_date  DATE NOT NULL,
    last_ingested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    chapter_count     INTEGER,
    section_count     INTEGER,
    notes             TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE wac.titles IS
  'One row per populated WAC title. LAZY-POPULATED at Phase 4 ingest time. '
  'publication_date = 2026-04-01 for current corpus.';


-- §1.2 wac.chapters
CREATE TABLE wac.chapters (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title_number     TEXT NOT NULL REFERENCES wac.titles(title_number),
    chapter_number   TEXT NOT NULL,
    chapter_heading  TEXT NOT NULL,
    sort_order       INTEGER NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (title_number, chapter_number)
);
COMMENT ON TABLE wac.chapters IS
  'One row per WAC chapter (e.g. 296-15, 296-14A). Dash format throughout.';


-- §1.3 wac.sections (with all CHECK constraints from inception)
CREATE TABLE wac.sections (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    document_id              UUID NOT NULL UNIQUE REFERENCES core.documents(id) ON DELETE CASCADE,
    title_number             TEXT NOT NULL REFERENCES wac.titles(title_number),
    chapter_id               UUID REFERENCES wac.chapters(id),
    section_number           TEXT NOT NULL,
    canonical_citation       TEXT NOT NULL,
    section_heading          TEXT NOT NULL,
    is_repealed              BOOLEAN NOT NULL DEFAULT FALSE,
    is_recodified            BOOLEAN NOT NULL DEFAULT FALSE,
    is_decodified            BOOLEAN NOT NULL DEFAULT FALSE,
    is_expired               BOOLEAN NOT NULL DEFAULT FALSE,
    is_reserved              BOOLEAN NOT NULL DEFAULT FALSE,
    recodified_to            TEXT,
    pending_recodification_to        TEXT,
    pending_recodification_effective DATE,
    effective_date           DATE,
    wsr_register_number      TEXT,
    full_text                TEXT,
    source_html              TEXT,
    publication_date         DATE NOT NULL,
    unit_type                TEXT NOT NULL DEFAULT 'section',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (canonical_citation, publication_date),

    CONSTRAINT chk_section_text_status_invariant CHECK (
      (full_text IS NOT NULL AND full_text <> ''
       AND NOT (is_repealed OR is_recodified OR is_decodified
                OR is_expired OR is_reserved))
      OR
      ((is_repealed OR is_recodified OR is_decodified
        OR is_expired OR is_reserved)
       AND (full_text IS NULL OR full_text = ''))
    ),

    CONSTRAINT chk_unit_type CHECK (unit_type IN ('section','reserved')),

    CONSTRAINT chk_recodified_target CHECK (
      NOT is_recodified OR (recodified_to IS NOT NULL AND recodified_to <> '')
    ),

    CONSTRAINT chk_pending_recodification_pair CHECK (
      (pending_recodification_to IS NULL AND pending_recodification_effective IS NULL)
      OR
      (pending_recodification_to IS NOT NULL AND pending_recodification_effective IS NOT NULL)
    )
);
COMMENT ON TABLE wac.sections IS
  'One row per WAC section (active + ghost). Three flavors mirroring rcw.sections. '
  'CHECK constraints are load-bearing audit channels per Phase 6 §K methodology.';


-- §1.4 wac.cross_references
CREATE TABLE wac.cross_references (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_section_id   UUID NOT NULL REFERENCES wac.sections(id) ON DELETE CASCADE,
    target_citation     TEXT NOT NULL,
    target_section_id   UUID REFERENCES wac.sections(id),
    target_jurisdiction TEXT NOT NULL,
    context_snippet     TEXT,
    ref_type            TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_target_jurisdiction CHECK (
      target_jurisdiction IN (
        'state-wa-rcw','federal-usc','state-wa-wac','cfr',
        'wa-court-rule','session-law','wa-constitution'
      )
    ),
    CONSTRAINT chk_ref_type CHECK (
      ref_type IN ('reference','recodification','cross-statute','see-also','authority')
    )
);
COMMENT ON TABLE wac.cross_references IS
  'Cross-citations from WAC section bodies. RCW citations in [Statutory '
  'Authority: ...] BRACKETS go to wac.authority_chain instead. '
  'target_jurisdiction enum is slug-aligned for code-jurisdiction values; '
  'matches harmonized rcw.cross_references CHECK (§HARMONIZE).';


-- §1.5 wac.section_history
CREATE TABLE wac.section_history (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_id      UUID NOT NULL REFERENCES wac.sections(id) ON DELETE CASCADE,
    wsr_register    TEXT NOT NULL,
    register_year   INTEGER,
    filed_date      DATE,
    effective_date  DATE,
    action_type     TEXT,
    action_summary  TEXT,
    sort_order      INTEGER NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_action_type CHECK (
      action_type IS NULL OR action_type IN ('adopted','amended','repealed','recodified','decodified','reorganized')
    )
);
COMMENT ON TABLE wac.section_history IS
  'Revision events from authority brackets and dispositions. sort_order=1 = most recent.';


-- §1.6 wac.section_notes
CREATE TABLE wac.section_notes (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_id    UUID NOT NULL REFERENCES wac.sections(id) ON DELETE CASCADE,
    note_type     TEXT NOT NULL,
    note_topic    TEXT,
    note_heading  TEXT,
    note_text     TEXT NOT NULL,
    sort_order    INTEGER NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE wac.section_notes IS
  'NOTES: blocks (if any). note_type permissive TEXT — Phase 0 sample size 4 '
  'did not surface any; structure preserved for parity with rcw.section_notes.';


-- §1.7 wac.ingestion_runs
CREATE TABLE wac.ingestion_runs (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    publication_date      DATE NOT NULL,
    started_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at          TIMESTAMPTZ,
    titles_planned        SMALLINT,
    titles_completed      SMALLINT,
    chapters_ingested     INTEGER,
    sections_ingested     INTEGER,
    chunks_ingested       INTEGER,
    embeddings_completed  INTEGER,
    authority_rows        INTEGER,
    status                TEXT NOT NULL DEFAULT 'running',
    notes                 TEXT,

    CONSTRAINT chk_ingestion_status CHECK (
      status IN ('running','completed','failed','partial','paused')
    )
);
COMMENT ON TABLE wac.ingestion_runs IS
  'One row per Phase 4 ingest invocation. authority_rows is WAC-specific.';


-- §1.8 wac.authority_chain (Option B per kickoff §4.3 + Phase 1 refinements)
CREATE TABLE wac.authority_chain (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wac_section_id    UUID NOT NULL REFERENCES wac.sections(id) ON DELETE CASCADE,
    authorizing_rcw   TEXT NOT NULL,
    rcw_section_id    UUID REFERENCES rcw.sections(id),
    authority_text    TEXT,
    is_chapter_level  BOOLEAN NOT NULL DEFAULT FALSE,
    is_session_law    BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order        INTEGER NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (wac_section_id, authorizing_rcw),

    CONSTRAINT chk_authority_xor CHECK (
      NOT (is_chapter_level AND is_session_law)
    )
);
COMMENT ON TABLE wac.authority_chain IS
  'WAC → RCW regulatory-authority chain. One row per RCW citation in each WAC '
  'section''s [Statutory Authority: ...] bracket. Doctrinally critical for '
  'reverse query "all WAC under RCW X.YY" via idx_wac_authority_rcw. '
  'is_chapter_level and is_session_law discriminate variants; chk_authority_xor '
  'enforces mutual exclusion.';


-- =============================================================================
-- §2  WAC INDEXES
-- =============================================================================

CREATE INDEX idx_wac_chapters_title              ON wac.chapters(title_number);
CREATE INDEX idx_wac_sections_title              ON wac.sections(title_number);
CREATE INDEX idx_wac_sections_chapter            ON wac.sections(chapter_id);
CREATE INDEX idx_wac_sections_citation           ON wac.sections(canonical_citation);
CREATE INDEX idx_wac_sections_publication        ON wac.sections(publication_date);

CREATE INDEX idx_wac_sections_repealed           ON wac.sections(canonical_citation) WHERE is_repealed   = TRUE;
CREATE INDEX idx_wac_sections_recodified         ON wac.sections(canonical_citation) WHERE is_recodified = TRUE;
CREATE INDEX idx_wac_sections_decodified         ON wac.sections(canonical_citation) WHERE is_decodified = TRUE;
CREATE INDEX idx_wac_sections_expired            ON wac.sections(canonical_citation) WHERE is_expired    = TRUE;
CREATE INDEX idx_wac_sections_reserved           ON wac.sections(canonical_citation) WHERE is_reserved   = TRUE;

CREATE INDEX idx_wac_sections_effective_date     ON wac.sections(effective_date) WHERE effective_date IS NOT NULL;
CREATE INDEX idx_wac_sections_unit_type          ON wac.sections(unit_type) WHERE unit_type <> 'section';
CREATE INDEX idx_wac_sections_recodified_to      ON wac.sections(recodified_to) WHERE recodified_to IS NOT NULL;

CREATE INDEX idx_wac_sections_pending_recodif_to
  ON wac.sections(pending_recodification_to)
  WHERE pending_recodification_to IS NOT NULL;
CREATE INDEX idx_wac_sections_pending_recodif_effective
  ON wac.sections(pending_recodification_effective)
  WHERE pending_recodification_effective IS NOT NULL;

CREATE INDEX idx_wac_sections_wsr                ON wac.sections(wsr_register_number) WHERE wsr_register_number IS NOT NULL;

CREATE INDEX idx_wac_sections_text_fts           ON wac.sections USING gin(to_tsvector('english', COALESCE(full_text,'')));

CREATE INDEX idx_wac_xref_source                 ON wac.cross_references(source_section_id);
CREATE INDEX idx_wac_xref_target                 ON wac.cross_references(target_citation);
CREATE INDEX idx_wac_xref_target_jurisdiction    ON wac.cross_references(target_jurisdiction);
CREATE INDEX idx_wac_xref_ref_type               ON wac.cross_references(ref_type);

CREATE INDEX idx_wac_history_section             ON wac.section_history(section_id);
CREATE INDEX idx_wac_history_wsr                 ON wac.section_history(wsr_register);
CREATE INDEX idx_wac_history_year                ON wac.section_history(register_year) WHERE register_year IS NOT NULL;

CREATE INDEX idx_wac_notes_section               ON wac.section_notes(section_id);
CREATE INDEX idx_wac_notes_type                  ON wac.section_notes(note_type);

CREATE INDEX idx_wac_authority_rcw               ON wac.authority_chain(authorizing_rcw);
CREATE INDEX idx_wac_authority_section           ON wac.authority_chain(wac_section_id);
CREATE INDEX idx_wac_authority_resolved          ON wac.authority_chain(rcw_section_id) WHERE rcw_section_id IS NOT NULL;


-- =============================================================================
-- §3  TAG TAXONOMY ADDITIONS
-- =============================================================================

-- §3a code-jurisdiction: state-wa-wac (one new slug)
INSERT INTO core.tags (slug, name, category, description) VALUES
  ('state-wa-wac', 'State WA WAC', 'code-jurisdiction',
   'Document is a section of the Washington Administrative Code (Washington State administrative regulations).')
ON CONFLICT (slug) DO NOTHING;


-- §3b wac-meta category (8 values)
INSERT INTO core.tags (slug, name, category, description) VALUES
  ('wac',              'WAC',              'wac-meta', 'Document is a section of the Washington Administrative Code.'),
  ('state-regulation', 'State Regulation', 'wac-meta', 'State-level administrative regulation (vs. federal CFR or court rule).'),
  ('wac-repealed',     'WAC Repealed',     'wac-meta', 'WAC section was repealed; preserved as ghost row.'),
  ('wac-recodified',   'WAC Recodified',   'wac-meta', 'WAC section was recodified to a different citation; ghost row carries recodified_to pointer.'),
  ('wac-decodified',   'WAC Decodified',   'wac-meta', 'WAC section was decodified (omitted from publication); ghost row preserved.'),
  ('wac-expired',      'WAC Expired',      'wac-meta', 'WAC section''s sunset clause fired; ghost row preserved.'),
  ('wac-reserved',     'WAC Reserved',     'wac-meta', 'WAC section number is reserved; never had text.'),
  ('wac-suspended',    'WAC Suspended',    'wac-meta', 'WAC section''s effective application is suspended pending some condition; rare.')
ON CONFLICT (slug) DO NOTHING;


-- §3c legal-framework topical tags — WAC additions (11 new values)
INSERT INTO core.tags (slug, name, category, description) VALUES
  ('wlad-enforcement-wac',
   'WLAD Enforcement (WAC)',
   'legal-framework',
   'WAC Title 162 — Human Rights Commission regulations enforcing RCW 49.60 (Washington Law Against Discrimination).'),
  ('bii-regulations-wac',
   'BII Regulations (WAC)',
   'legal-framework',
   'WAC Title 296 — Department of Labor & Industries regulations implementing RCW Title 51 (industrial insurance / workers'' compensation).'),
  ('dshs-wac',
   'DSHS Regulations (WAC)',
   'legal-framework',
   'WAC Title 388 — Department of Social and Health Services regulations implementing RCW Title 74 (public assistance, child welfare, long-term care).'),
  ('dcyf-wac',
   'DCYF Regulations (WAC)',
   'legal-framework',
   'WAC Title 110 — Department of Children, Youth and Families regulations implementing RCW chapter 26.44 (child abuse) and RCW Title 74 (foster care, adoption).'),
  ('hca-wac',
   'HCA Regulations (WAC)',
   'legal-framework',
   'WAC Title 182 — Health Care Authority regulations implementing RCW chapter 41.05 (Apple Health, employee benefits) and RCW Title 71 (behavioral health).'),
  ('doh-wac',
   'DOH Regulations (WAC)',
   'legal-framework',
   'WAC Title 246 — Department of Health regulations implementing RCW Title 18 (medical practice acts) and RCW Title 70 (public health).'),
  ('civil-service-wac',
   'Civil Service Regulations (WAC)',
   'legal-framework',
   'WAC Title 357 — State Human Resources / civil service regulations implementing RCW chapter 41.06.'),
  ('employment-security-wac',
   'Employment Security Regulations (WAC)',
   'legal-framework',
   'WAC Title 192 — Employment Security Department regulations implementing RCW Title 50 (unemployment insurance) and Title 50A (paid family medical leave).'),
  ('licensing-wac',
   'Licensing Regulations (WAC)',
   'legal-framework',
   'WAC Title 308 — Department of Licensing regulations across professional licensing, vehicle licensing, and related domains.'),
  ('revenue-wac',
   'Revenue Regulations (WAC)',
   'legal-framework',
   'WAC Title 458 — Department of Revenue regulations implementing RCW Title 82 (excise taxes), Title 84 (property taxes), and Title 83 (estate taxation).'),
  ('pra-regulations-wac',
   'PRA Regulations (WAC)',
   'legal-framework',
   'Cross-cutting WAC chapters implementing RCW chapter 42.56 (Public Records Act) — each agency publishes its own PRA-implementation WAC under its respective title.')
ON CONFLICT (slug) DO NOTHING;


-- §3d wac-title category — INTENTIONALLY EMPTY at apply (lazy-populated Phase 4)


-- =============================================================================
-- §POST-APPLY GUARDS
-- =============================================================================

DO $$
DECLARE
  tables_count             INTEGER;
  cj_count                 INTEGER;
  wac_meta_count           INTEGER;
  wac_title_count          INTEGER;
  topical_count            INTEGER;
  total_legal_framework    INTEGER;
  rcw_section_count        INTEGER;
  usc_tag_count            INTEGER;
  rcw_tag_count            INTEGER;
  wac_tag_count            INTEGER;
  chk_count                INTEGER;
  rcw_check_def            TEXT;
  wac_check_def            TEXT;
BEGIN
  -- §POST.1 All 8 wac.* tables exist
  SELECT COUNT(*) INTO tables_count FROM information_schema.tables
    WHERE table_schema='wac'
      AND table_name IN (
        'titles','chapters','sections','cross_references',
        'section_history','section_notes','ingestion_runs','authority_chain'
      );
  IF tables_count <> 8 THEN
    RAISE EXCEPTION 'Post-apply FAIL: wac schema has % expected tables, got %.', 8, tables_count;
  END IF;

  -- §POST.2 code-jurisdiction now has 3 rows (federal-usc, state-wa-rcw, state-wa-wac)
  SELECT COUNT(*) INTO cj_count FROM core.tags WHERE category='code-jurisdiction';
  IF cj_count <> 3 THEN
    RAISE EXCEPTION 'Post-apply FAIL: code-jurisdiction has % rows, expected 3.', cj_count;
  END IF;

  -- §POST.3 wac-meta has 8 rows
  SELECT COUNT(*) INTO wac_meta_count FROM core.tags WHERE category='wac-meta';
  IF wac_meta_count <> 8 THEN
    RAISE EXCEPTION 'Post-apply FAIL: wac-meta has % rows, expected 8.', wac_meta_count;
  END IF;

  -- §POST.4 wac-title intentionally still empty (lazy-populated)
  SELECT COUNT(*) INTO wac_title_count FROM core.tags WHERE category='wac-title';
  IF wac_title_count <> 0 THEN
    RAISE EXCEPTION 'Post-apply FAIL: wac-title has % rows, expected 0 (lazy-populated).', wac_title_count;
  END IF;

  -- §POST.5 11 new legal-framework topical tags inserted
  SELECT COUNT(*) INTO topical_count FROM core.tags WHERE category='legal-framework' AND slug LIKE '%-wac';
  IF topical_count <> 11 THEN
    RAISE EXCEPTION 'Post-apply FAIL: %-wac topical tag count is %, expected 11.', topical_count, 11;
  END IF;
  SELECT COUNT(*) INTO total_legal_framework FROM core.tags WHERE category='legal-framework';
  -- Total legal-framework = (28 federal from USC Phase 1) + (17 RCW from RCW Phase 1) + (11 WAC) = 56
  IF total_legal_framework <> 56 THEN
    RAISE EXCEPTION 'Post-apply FAIL: total legal-framework is %, expected 56 (28+17+11).', total_legal_framework;
  END IF;

  -- §POST.6 RCW + USC corpora unchanged
  SELECT COUNT(*) INTO rcw_section_count FROM rcw.sections;
  IF rcw_section_count <> 51764 THEN
    RAISE EXCEPTION 'Post-apply FAIL: rcw.sections changed from 51,764 to %.', rcw_section_count;
  END IF;
  SELECT COUNT(*) INTO usc_tag_count FROM core.document_tags dt
    JOIN core.tags t ON t.id=dt.tag_id
    WHERE t.category='code-jurisdiction' AND t.slug='federal-usc';
  IF usc_tag_count <> 11678 THEN
    RAISE EXCEPTION 'Post-apply FAIL: USC code-jurisdiction tag count changed from 11,678 to %.', usc_tag_count;
  END IF;
  SELECT COUNT(*) INTO rcw_tag_count FROM core.document_tags dt
    JOIN core.tags t ON t.id=dt.tag_id
    WHERE t.category='code-jurisdiction' AND t.slug='state-wa-rcw';
  IF rcw_tag_count <> 51764 THEN
    RAISE EXCEPTION 'Post-apply FAIL: RCW code-jurisdiction tag count changed from 51,764 to %.', rcw_tag_count;
  END IF;

  -- §POST.7 No documents tagged with state-wa-wac yet (Phase 4 will populate)
  SELECT COUNT(*) INTO wac_tag_count FROM core.document_tags dt
    JOIN core.tags t ON t.id=dt.tag_id
    WHERE t.category='code-jurisdiction' AND t.slug='state-wa-wac';
  IF wac_tag_count <> 0 THEN
    RAISE EXCEPTION 'Post-apply FAIL: state-wa-wac has % doc-tag associations, expected 0 pre-Phase-4.', wac_tag_count;
  END IF;

  -- §POST.8 Critical CHECK constraints registered
  SELECT COUNT(*) INTO chk_count FROM pg_constraint
    WHERE conname IN (
      'chk_section_text_status_invariant','chk_recodified_target',
      'chk_pending_recodification_pair','chk_unit_type','chk_authority_xor'
    )
    AND conrelid IN ('wac.sections'::regclass, 'wac.authority_chain'::regclass);
  IF chk_count <> 5 THEN
    RAISE EXCEPTION 'Post-apply FAIL: % of expected 5 CHECK constraints registered.', chk_count;
  END IF;

  -- §POST.9 Harmonized CHECK enums on BOTH cross-references tables include
  --         'state-wa-wac' and DO NOT include 'wac' short form.
  SELECT pg_get_constraintdef(oid) INTO rcw_check_def FROM pg_constraint
    WHERE conname='chk_target_jurisdiction' AND conrelid='rcw.cross_references'::regclass;
  IF rcw_check_def NOT LIKE '%state-wa-wac%' THEN
    RAISE EXCEPTION 'Post-apply FAIL: rcw.cross_references CHECK does not include ''state-wa-wac''. Got: %', rcw_check_def;
  END IF;
  IF rcw_check_def LIKE '%''wac''%' THEN
    RAISE EXCEPTION 'Post-apply FAIL: rcw.cross_references CHECK still includes short-form ''wac''. Got: %', rcw_check_def;
  END IF;
  SELECT pg_get_constraintdef(oid) INTO wac_check_def FROM pg_constraint
    WHERE conname='chk_target_jurisdiction' AND conrelid='wac.cross_references'::regclass;
  IF wac_check_def NOT LIKE '%state-wa-wac%' THEN
    RAISE EXCEPTION 'Post-apply FAIL: wac.cross_references CHECK does not include ''state-wa-wac''. Got: %', wac_check_def;
  END IF;
  IF wac_check_def LIKE '%''wac''%' THEN
    RAISE EXCEPTION 'Post-apply FAIL: wac.cross_references CHECK still includes short-form ''wac''. Got: %', wac_check_def;
  END IF;

  RAISE NOTICE 'Post-apply guards: PASS (8 wac tables; 3 code-juris; 8 wac-meta; 0 wac-title; 11 wac topical; 5 CHECKs; RCW/USC unchanged; both cross_refs CHECKs harmonized to state-wa-wac)';
END $$;


-- =============================================================================
-- COMMIT
-- =============================================================================

COMMIT;


-- =============================================================================
-- §VERIFICATION SELECTs (post-commit, for operator review)
-- =============================================================================

\echo ''
\echo '--- §V.1 wac schema and 8 tables ---'
SELECT
  EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name='wac')                                               AS wac_schema,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='titles')           AS titles_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='chapters')         AS chapters_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='sections')         AS sections_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='cross_references') AS xref_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='section_history')  AS history_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='section_notes')    AS notes_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='ingestion_runs')   AS runs_tbl,
  EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='wac' AND table_name='authority_chain')  AS authority_tbl;

\echo ''
\echo '--- §V.2 Tag categories (expect 3 / 8 / 0 / 56) ---'
SELECT
  (SELECT COUNT(*) FROM core.tags WHERE category='code-jurisdiction')   AS code_jurisdiction_n,
  (SELECT COUNT(*) FROM core.tags WHERE category='wac-meta')            AS wac_meta_n,
  (SELECT COUNT(*) FROM core.tags WHERE category='wac-title')           AS wac_title_n,
  (SELECT COUNT(*) FROM core.tags WHERE category='legal-framework')     AS legal_framework_total;

\echo ''
\echo '--- §V.3 RCW + USC corpora unchanged (51,764 + 11,678) ---'
SELECT
  (SELECT COUNT(*) FROM rcw.sections)                                                                       AS rcw_sections,
  (SELECT COUNT(*) FROM core.document_tags dt JOIN core.tags t ON t.id=dt.tag_id WHERE t.slug='federal-usc')  AS usc_tag_count,
  (SELECT COUNT(*) FROM core.document_tags dt JOIN core.tags t ON t.id=dt.tag_id WHERE t.slug='state-wa-rcw') AS rcw_tag_count,
  (SELECT COUNT(*) FROM core.document_tags dt JOIN core.tags t ON t.id=dt.tag_id WHERE t.slug='state-wa-wac') AS wac_tag_count;  -- expect 0

\echo ''
\echo '--- §V.4 CHECK constraints (5 critical) ---'
SELECT conname, conrelid::regclass::text AS table_name FROM pg_constraint
WHERE conname IN (
  'chk_section_text_status_invariant','chk_recodified_target',
  'chk_pending_recodification_pair','chk_unit_type','chk_authority_xor'
)
AND conrelid IN ('wac.sections'::regclass, 'wac.authority_chain'::regclass)
ORDER BY conname;

\echo ''
\echo '--- §V.5 New legal-framework WAC topical tags (expect 11) ---'
SELECT slug FROM core.tags WHERE category='legal-framework' AND slug LIKE '%-wac' ORDER BY slug;

\echo ''
\echo '--- §V.6 Harmonized cross-references CHECK enums (both tables; both contain state-wa-wac, neither contains short ''wac'') ---'
SELECT
  conrelid::regclass::text AS table_name,
  pg_get_constraintdef(oid) AS check_def
FROM pg_constraint
WHERE conname='chk_target_jurisdiction'
  AND conrelid IN ('rcw.cross_references'::regclass, 'wac.cross_references'::regclass)
ORDER BY table_name;

\echo ''
\echo '=== END schema_apply.sql ==='
